#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Verify SRI integrity attributes on CDN resources in frontend HTML files."""

import re
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[3]  # tests/ → provide-terminal/ → packages/ → repo root
FRONTEND_DIR = _REPO_ROOT / "packages/provide-terminal-server/src/provide/terminal/server/frontend"
CF_FRONTEND_DIR = _REPO_ROOT / "packages/provide-terminal-cloudflare/python_modules/provide/terminal/frontend"
DEMO_DIR = _REPO_ROOT / "demo"

_JSDELIVR = r"<(?:script|link)[^>]+cdn\.jsdelivr\.net[^>]+>"

_skip_no_build = pytest.mark.skipif(
    not (FRONTEND_DIR / "terminal.html").exists(),
    reason="frontend not built — run `npm run build:frontend` first",
)
_skip_no_cf = pytest.mark.skipif(
    not (CF_FRONTEND_DIR / "terminal.html").exists(),
    reason="CF frontend files not present",
)
_skip_no_demo = pytest.mark.skipif(
    not (DEMO_DIR / "terminal.html").exists(),
    reason="demo/terminal.html not present",
)


def _check_sri(tags: list[str], source: str) -> None:
    for tag in tags:
        assert 'integrity="sha384-' in tag, f"Missing SRI integrity in {source}: {tag}"
        assert 'crossorigin="anonymous"' in tag, f"Missing crossorigin in {source}: {tag}"


# ── build-output copies (gitignored, generated by npm run build:frontend) ───


@_skip_no_build
def test_terminal_html_scripts_have_integrity() -> None:
    html = (FRONTEND_DIR / "terminal.html").read_text()
    scripts = re.findall(r"<script[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert scripts, "Expected CDN script tags in terminal.html"
    _check_sri(scripts, "terminal.html")


@_skip_no_build
def test_terminal_html_stylesheets_have_integrity() -> None:
    html = (FRONTEND_DIR / "terminal.html").read_text()
    links = re.findall(r"<link[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert links, "Expected CDN stylesheet link tags in terminal.html"
    _check_sri(links, "terminal.html")


@_skip_no_build
def test_terminal_html_google_fonts_no_integrity() -> None:
    html = (FRONTEND_DIR / "terminal.html").read_text()
    fonts_links = re.findall(r"<link[^>]+fonts\.googleapis\.com[^>]+>", html)
    for tag in fonts_links:
        assert "integrity=" not in tag, f"Google Fonts should not have SRI: {tag}"


@_skip_no_build
def test_hijack_html_scripts_have_integrity() -> None:
    html = (FRONTEND_DIR / "hijack.html").read_text()
    scripts = re.findall(r"<script[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert scripts, "Expected CDN script tags in hijack.html"
    _check_sri(scripts, "hijack.html")


@_skip_no_build
def test_hijack_html_stylesheets_have_integrity() -> None:
    html = (FRONTEND_DIR / "hijack.html").read_text()
    links = re.findall(r"<link[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert links, "Expected CDN stylesheet link tags in hijack.html"
    _check_sri(links, "hijack.html")


@_skip_no_build
def test_hijack_html_google_fonts_no_integrity() -> None:
    html = (FRONTEND_DIR / "hijack.html").read_text()
    fonts_links = re.findall(r"<link[^>]+fonts\.googleapis\.com[^>]+>", html)
    for tag in fonts_links:
        assert "integrity=" not in tag, f"Google Fonts should not have SRI: {tag}"


# ── CF vendored copies (tracked in git, must stay in sync) ──────────────────


@_skip_no_cf
def test_cf_terminal_html_cdn_tags_have_integrity() -> None:
    html = (CF_FRONTEND_DIR / "terminal.html").read_text()
    tags = re.findall(_JSDELIVR, html)
    assert tags, "Expected CDN tags in CF python_modules terminal.html"
    _check_sri(tags, "CF terminal.html")


@_skip_no_cf
def test_cf_hijack_html_cdn_tags_have_integrity() -> None:
    html = (CF_FRONTEND_DIR / "hijack.html").read_text()
    tags = re.findall(_JSDELIVR, html)
    assert tags, "Expected CDN tags in CF python_modules hijack.html"
    _check_sri(tags, "CF hijack.html")


# ── demo viewer (tracked in git, older xterm version) ───────────────────────


@_skip_no_demo
def test_demo_terminal_html_cdn_tags_have_integrity() -> None:
    html = (DEMO_DIR / "terminal.html").read_text()
    tags = re.findall(_JSDELIVR, html)
    assert tags, "Expected CDN tags in demo/terminal.html"
    _check_sri(tags, "demo/terminal.html")
