//
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later
//

package serverauth

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/provide-io/provide-uterm/packages/provide-uterm-go/serverconfig"
)

// parityGoldens mirrors testdata/parity_goldens.json, generated by the Python
// signer/JWT (scripts/gen_goldens.py). These prove the Go implementation
// produces/accepts values identical to the Python server byte-for-byte.
type parityGoldens struct {
	HMACSecret string `json:"hmac_secret"`
	HMACCases  []struct {
		Secret    string `json:"secret"`
		BodyUTF8  string `json:"body_utf8"`
		Timestamp string `json:"timestamp"`
		Signature string `json:"signature"`
	} `json:"hmac_cases"`
	JWTHS256 struct {
		Secret         string   `json:"secret"`
		Token          string   `json:"token"`
		Sub            string   `json:"sub"`
		Issuer         string   `json:"issuer"`
		Audience       string   `json:"audience"`
		ExpectedRoles  []string `json:"expected_roles"`
		ExpectedScopes []string `json:"expected_scopes"`
	} `json:"jwt_hs256"`
}

func loadGoldens(t *testing.T) parityGoldens {
	t.Helper()
	raw, err := os.ReadFile("testdata/parity_goldens.json")
	if err != nil {
		t.Fatal(err)
	}
	var g parityGoldens
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

func TestHMACSignatureParityWithPython(t *testing.T) {
	g := loadGoldens(t)
	for _, c := range g.HMACCases {
		got := BuildWebhookSignature(c.Secret, []byte(c.BodyUTF8), c.Timestamp)
		if got != c.Signature {
			t.Errorf("BuildWebhookSignature(body=%q ts=%q)\n  got  %s\n  want %s (Python)",
				c.BodyUTF8, c.Timestamp, got, c.Signature)
		}
		// And Go must accept the Python-produced signature.
		now := parseTS(c.Timestamp)
		if !VerifyWebhookSignature(c.Secret, []byte(c.BodyUTF8), c.Signature, c.Timestamp, DefaultMaxAgeS, &now) {
			t.Errorf("Go rejected a valid Python signature for body=%q", c.BodyUTF8)
		}
	}
}

func TestJWTSignatureParityWithPython(t *testing.T) {
	g := loadGoldens(t)
	key := g.JWTHS256.Secret
	idp := NewLocalIdentityProvider(&serverconfig.AuthConfig{
		Mode: "jwt", JWTPublicKeyPEM: &key, JWTAlgorithms: []string{"HS256"},
		JWTIssuer: g.JWTHS256.Issuer, JWTAudience: g.JWTHS256.Audience,
		JWTRolesClaim: "roles", JWTScopesClaim: "scope", ClockSkewSeconds: 15,
	}, nil)

	p, err := idp.PrincipalFromJWTToken(g.JWTHS256.Token)
	if err != nil {
		t.Fatalf("Go rejected a valid Python-minted JWT: %v", err)
	}
	if p.SubjectID != g.JWTHS256.Sub {
		t.Errorf("sub = %q, want %q", p.SubjectID, g.JWTHS256.Sub)
	}
	for _, role := range g.JWTHS256.ExpectedRoles {
		if !p.Roles.Has(role) {
			t.Errorf("missing role %q from Python token; got %v", role, p.Roles.Sorted())
		}
	}
	for _, scope := range g.JWTHS256.ExpectedScopes {
		if !p.Scopes.Has(scope) {
			t.Errorf("missing scope %q; got %v", scope, p.Scopes.Sorted())
		}
	}
}

func parseTS(s string) float64 {
	var v float64
	// tolerate both "1700000000" and "1700000000.0"
	if _, err := jsonNumber(s, &v); err != nil {
		return 0
	}
	return v
}

func jsonNumber(s string, out *float64) (bool, error) {
	return true, json.Unmarshal([]byte(s), out)
}
