//
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later
//

using System.Globalization;
using System.Net.Sockets;
using System.Text.Json;
using Provide.Uterm.Transports;

namespace Provide.Uterm.Tests;

/// <summary>
/// <see cref="ReconnectingTransport"/> held to reconnect_golden.json, the corpus the
/// TypeScript port is tested against, generated by driving the real Python
/// <c>ReconnectingSession</c> (packages/provide-uterm-ts/testdata/gen_reconnect_golden.py;
/// the copy under testdata is kept identical by <see cref="SharedCorpusParityTests"/>).
/// The corpus is session-level; at the transport level a session's connect, close and
/// send are the inner transport's ConnectAsync, DisconnectAsync and SendAsync.
/// </summary>
public class TermSessionReconnectGoldenTests
{
    private static readonly JsonElement Golden = Load();

    /// <summary>
    /// Each Python exception in the corpus's classification, as the .NET exception the same
    /// failure arrives as. A corpus entry missing here fails
    /// <see cref="EveryClassifiedErrorHasADotNetCounterpart"/> rather than being skipped.
    /// </summary>
    private static readonly Dictionary<string, Exception> DotNetCounterpart = new()
    {
        ["ConnectionError"] = new IOException("dropped"),
        ["BrokenPipeError"] = new SocketException((int)SocketError.Shutdown),
        ["ConnectionResetError"] = new SocketException((int)SocketError.ConnectionReset),
        ["ConnectionRefusedError"] = new SocketException((int)SocketError.ConnectionRefused),
        ["ConnectionAbortedError"] = new SocketException((int)SocketError.ConnectionAborted),
        ["OSError"] = new IOException("host unreachable"),
        ["TimeoutError"] = new TimeoutException("took too long"),
        ["FileNotFoundError"] = new FileNotFoundException("no such file"),
        ["PermissionError"] = new UnauthorizedAccessException("denied"),
        ["InterruptedError"] = new SocketException((int)SocketError.Interrupted),
        ["ValueError"] = new ArgumentException("bad value"),
        ["TypeError"] = new InvalidCastException("bad type"),
        ["KeyError"] = new KeyNotFoundException("missing"),
        ["RuntimeError"] = new InvalidOperationException("broken"),
        ["AssertionError"] = new System.Diagnostics.UnreachableException("impossible"),
        ["Exception"] = new Exception("something"),
    };

    private static JsonElement Load()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "testdata", "reconnect_golden.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.Clone();
    }

    private static IEnumerable<JsonElement> Items(string key) => Golden.GetProperty(key).EnumerateArray();

    private static JsonElement Named(string key, string name) =>
        Items(key).Single(v => v.GetProperty("name").GetString() == name);

    private static TheoryData<string> Names(string key)
    {
        var data = new TheoryData<string>();
        foreach (var item in Items(key))
        {
            data.Add(item.GetProperty("name").GetString()!);
        }

        return data;
    }

    public static TheoryData<string> ScheduleNames() => Names("schedules");

    public static TheoryData<string> ClassificationNames() => Names("classification");

    public static TheoryData<string> SequenceNames() => Names("sequences");

    private static ReconnectPolicy PolicyOf(JsonElement e) => new(
        e.GetProperty("max_retries").GetInt32(),
        TimeSpan.FromSeconds(e.GetProperty("base_backoff_s").GetDouble()),
        TimeSpan.FromSeconds(e.GetProperty("max_backoff_s").GetDouble()));

    private static string Seconds(double value) => value.ToString("R", CultureInfo.InvariantCulture);

    [Fact]
    public void TheDefaultPolicyMatchesTheReference() =>
        Assert.Equal(PolicyOf(Golden.GetProperty("defaults")), ReconnectPolicy.Default);

    [Fact]
    public void TheExhaustedMessagesMatchTheReference()
    {
        Assert.Equal(RetriesExhaustedException.ReconnectMessage, Golden.GetProperty("exhausted_message").GetString());
        Assert.Equal(
            RetriesExhaustedException.ConnectMessage, Golden.GetProperty("connect_exhausted_message").GetString());
    }

    [Theory]
    [MemberData(nameof(ScheduleNames))]
    public void TheBackoffScheduleMatchesTheReference(string name)
    {
        var schedule = Named("schedules", name);
        var policy = PolicyOf(schedule);
        var want = schedule.GetProperty("delays").EnumerateArray().Select(d => Seconds(d.GetDouble())).ToList();
        var got = Enumerable.Range(0, want.Count).Select(attempt => Seconds(policy.Delay(attempt).TotalSeconds)).ToList();
        Assert.Equal(want, got);
    }

    [Fact]
    public void EveryClassifiedErrorHasADotNetCounterpart()
    {
        var missing = Items("classification")
            .Select(c => c.GetProperty("error").GetString()!)
            .Where(error => !DotNetCounterpart.ContainsKey(error))
            .ToList();
        Assert.Empty(missing);
    }

    [Theory]
    [MemberData(nameof(ClassificationNames))]
    public void TheRetryableSetMatchesTheReference(string name)
    {
        var entry = Named("classification", name);
        var error = DotNetCounterpart[entry.GetProperty("error").GetString()!];
        Assert.Equal(entry.GetProperty("retryable").GetBoolean(), ReconnectingTransport.IsRetryable(error));
    }

    [Theory]
    [MemberData(nameof(SequenceNames))]
    public async Task TheSequenceMatchesTheReference(string name)
    {
        var sequence = Named("sequences", name);
        var (log, error) = await DriveAsync(name);

        var want = sequence.GetProperty("log").EnumerateArray().Select(Render).ToList();
        Assert.Equal(want, log);

        if (sequence.GetProperty("error").ValueKind == JsonValueKind.Null)
        {
            Assert.Null(error);
            return;
        }

        Assert.NotNull(error);
        var expectedType = DotNetCounterpart[sequence.GetProperty("error").GetString()!].GetType();
        Assert.IsAssignableFrom(expectedType, error);
        Assert.Equal(sequence.GetProperty("message").GetString(), error.Message);
    }

    private static string Render(JsonElement step) =>
        string.Join(
            " ",
            step.EnumerateArray().Select(part =>
                part.ValueKind == JsonValueKind.Number ? Seconds(part.GetDouble()) : part.GetString()));

    /// <summary>The sequence cases' inputs, from the generator's SEQUENCE_CASES.</summary>
    private sealed record SequenceCase(
        int MaxRetries,
        double BaseBackoffS,
        double MaxBackoffS,
        string[]? ConnectFailures = null,
        Dictionary<int, string[]>? SendFailures = null,
        bool CloseFails = false,
        bool Hook = true);

    private static readonly Dictionary<int, string[]> DropOnce = new() { [0] = ["connection"] };

    private static readonly Dictionary<string, SequenceCase> Cases = new()
    {
        ["a send that works"] = new(5, 0.5, 30.0),
        ["a socket that drops once"] = new(5, 0.5, 30.0, SendFailures: DropOnce),
        ["a socket that drops on an OSError"] = new(5, 0.5, 30.0, SendFailures: new() { [0] = ["os"] }),
        ["the caller's own bug"] = new(5, 0.5, 30.0, SendFailures: new() { [0] = ["value"] }),
        ["a socket that drops twice"] = new(
            5, 0.5, 30.0, SendFailures: new() { [0] = ["connection"], [1] = ["connection"] }),
        ["a session that never stays up"] = new(
            2, 0.5, 30.0, SendFailures: Enumerable.Range(0, 6).ToDictionary(i => i, _ => new[] { "connection" })),
        ["a server that is hard down"] = new(2, 0.5, 30.0, ConnectFailures: Enumerable.Repeat("refused", 6).ToArray()),
        ["a server down for the first attempt only"] = new(2, 0.5, 30.0, ConnectFailures: ["refused"]),
        ["a drop, then a server that will not come back"] = new(
            1, 0.5, 30.0, ConnectFailures: ["ok", "refused", "refused", "refused"], SendFailures: DropOnce),
        ["no retries allowed at all"] = new(0, 0.5, 30.0, SendFailures: DropOnce),
        ["no backoff configured"] = new(5, 0.0, 30.0, SendFailures: DropOnce),
        ["a ceiling below the base"] = new(
            3, 4.0, 1.0, SendFailures: new() { [0] = ["connection"], [1] = ["connection"], [2] = ["connection"] }),
        ["a session whose close fails on the way out"] = new(5, 0.5, 30.0, SendFailures: DropOnce, CloseFails: true),
        ["a drop with nobody watching for the reconnect"] = new(5, 0.5, 30.0, SendFailures: DropOnce, Hook: false),
    };

    [Fact]
    public void EverySequenceInTheCorpusHasItsInputsHere() =>
        Assert.Equal(
            Items("sequences").Select(s => s.GetProperty("name").GetString()!).OrderBy(n => n, StringComparer.Ordinal),
            Cases.Keys.OrderBy(n => n, StringComparer.Ordinal));

    /// <summary>Connect, then send once, recording every step the wrapper takes.</summary>
    private static async Task<(List<string> Log, Exception? Error)> DriveAsync(string name)
    {
        var c = Cases[name];
        var log = new List<string>();
        var attempts = 0;
        var rt = new ReconnectingTransport(
            () =>
            {
                var index = attempts++;
                var failures = c.ConnectFailures ?? [];
                return new RecordingTransport(
                    log,
                    $"session-{index}",
                    index < failures.Length ? failures[index] : "ok",
                    c.SendFailures?.GetValueOrDefault(index) ?? [],
                    c.CloseFails);
            },
            new ReconnectingOptions
            {
                Policy = new ReconnectPolicy(
                    c.MaxRetries, TimeSpan.FromSeconds(c.BaseBackoffS), TimeSpan.FromSeconds(c.MaxBackoffS)),
                Sleep = (delay, _) =>
                {
                    log.Add($"sleep {Seconds(delay.TotalSeconds)}");
                    return Task.CompletedTask;
                },
                OnReconnect = c.Hook
                    ? (inner, _) =>
                    {
                        log.Add($"hook {((RecordingTransport)inner).Name}");
                        return Task.CompletedTask;
                    }
                    : null,
            });

        try
        {
            await rt.ConnectAsync("h", 1);
            await rt.SendAsync("hello"u8.ToArray());
            return (log, null);
        }
        catch (Exception ex)
        {
            return (log, ex);
        }
    }

    /// <summary>A transport recording what was asked of it, failing on cue (the generator's RecordingSession).</summary>
    private sealed class RecordingTransport(
        List<string> log, string name, string connectFailure, string[] sendFailures, bool closeFails)
        : IConnectionTransport
    {
        private int _sends;

        public string Name => name;

        public Task ConnectAsync(string host, int port, ConnectOptions? options = null, CancellationToken cancellationToken = default)
        {
            log.Add($"connect {connectFailure}");
            return connectFailure == "ok" ? Task.CompletedTask : throw new IOException(connectFailure);
        }

        public Task DisconnectAsync(CancellationToken cancellationToken = default)
        {
            if (closeFails)
            {
                log.Add($"close {name} raised");
                throw new IOException("already gone");
            }

            log.Add($"close {name}");
            return Task.CompletedTask;
        }

        public Task SendAsync(byte[] data, CancellationToken cancellationToken = default)
        {
            var index = _sends++;
            var failure = index < sendFailures.Length ? sendFailures[index] : "ok";
            log.Add($"send {name} {failure}");
            return failure switch
            {
                "connection" => throw new IOException("socket went away"),
                "os" => throw new SocketException((int)SocketError.HostUnreachable),
                "value" => throw new ArgumentException("the caller's own bug"),
                _ => Task.CompletedTask,
            };
        }

        public Task<byte[]> ReceiveAsync(int maxBytes, TimeSpan timeout, CancellationToken cancellationToken = default) =>
            Task.FromResult(Array.Empty<byte>());

        public bool IsConnected() => true;
    }
}
