//
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later
//

/**
 * The server's JWT path, held to `serverjwt_golden`.
 *
 * The corpus is generated by driving the reference's own
 * `LocalIdentityProvider._principal_from_jwt_token` over every way a token can
 * be right and every way it can be wrong, so what is compared here is not a
 * reading of PyJWT's documentation but PyJWT's behaviour.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { decodeJwt, encodeJwt, JwtError } from "./jwt.ts";
import {
  type AuthSettings,
  anonymousPrincipal,
  extractBearerToken,
  principalFromJwtToken,
  resolveJwtPrincipal,
} from "./principal.ts";

interface Vector {
  name: string;
  token: string;
  why: string;
  settings?: Partial<AuthSettings>;
  result:
    | { accepted: true; subject_id: string; tenant_id: string | null; roles: string[]; scopes: string[] }
    | { accepted: false; error_type: string; error: string };
}

interface DecodeVector {
  name: string;
  token: string;
  why: string;
  args: {
    algorithms: string[];
    issuer: string | null;
    audience: string | null;
    leeway: number;
    require?: string[];
    now?: number;
  };
  result: { accepted: true; claims: Record<string, unknown> } | { accepted: false; error_type: string; error: string };
}

interface Corpus {
  secret: string;
  other_secret: string;
  issuer: string;
  audience: string;
  clock_skew_seconds: number;
  future_exp: number;
  past_exp: number;
  vectors: Vector[];
  edge_vectors: Vector[];
  decode_vectors: DecodeVector[];
  bearer_headers: { header: string; token: string | null }[];
}

const CORPUS = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "..", "testdata", "serverjwt_golden.json"), "utf8"),
) as Corpus;

/** The auth settings the corpus was recorded under. */
const SETTINGS: AuthSettings = {
  jwt_public_key_pem: CORPUS.secret,
  jwt_algorithms: ["HS256"],
  jwt_issuer: CORPUS.issuer,
  jwt_audience: CORPUS.audience,
  jwt_roles_claim: "roles",
  jwt_scopes_claim: "scope",
  jwt_tenant_claim: "tenant_id",
  clock_skew_seconds: CORPUS.clock_skew_seconds,
};

/** A header lookup over a plain record, which is what `Headers` gives. */
function headers(values: Record<string, string>): { get(name: string): string | null } {
  return { get: (name) => values[name] ?? null };
}

/**
 * The one vector whose refusal *message* this port cannot reproduce.
 *
 * The reference's text is CPython's codec error — `'utf-8' codec can't decode
 * byte 0x9e in position 0: invalid start byte` — reached because
 * `json.loads` is handed bytes. Reproducing it would mean porting CPython's
 * UTF-8 error taxonomy for a string that never leaves the process: it is
 * logged, never served. The refusal *kind* is what the wire depends on, and
 * that is asserted for this vector like every other.
 */
const CODEC_MESSAGE_VECTOR = "not_a_token";

describe("the token vectors the reference recorded", () => {
  it("covers every vector, so a corpus that shrank is visible", () => {
    expect(CORPUS.vectors.length).toBe(24);
  });

  for (const vector of CORPUS.vectors) {
    // The keyless vector is the one recorded under a different config: a
    // deployment in jwt mode that configured nothing to verify with.
    const settings = vector.name === "no_key_configured" ? { ...SETTINGS, jwt_public_key_pem: null } : SETTINGS;
    // Pinned between the corpus's two fixed instants, so a vector's verdict
    // is the same whenever the suite runs.
    const now = () => (CORPUS.past_exp + CORPUS.future_exp) / 2;

    if (vector.result.accepted) {
      const expected = vector.result;
      it(`accepts ${vector.name}: ${vector.why}`, () => {
        const principal = principalFromJwtToken(vector.token, settings, now);
        expect(principal.subject_id).toBe(expected.subject_id);
        expect(principal.tenant_id).toBe(expected.tenant_id);
        expect([...principal.roles].sort()).toEqual(expected.roles);
        expect([...principal.scopes].sort()).toEqual(expected.scopes);
      });
      continue;
    }

    const expected = vector.result;
    it(`refuses ${vector.name}: ${vector.why}`, () => {
      let thrown: unknown;
      try {
        principalFromJwtToken(vector.token, settings, now);
      } catch (error) {
        thrown = error;
      }
      expect(thrown).toBeInstanceOf(JwtError);
      expect((thrown as JwtError).code).toBe(expected.error_type);
      if (vector.name === CODEC_MESSAGE_VECTOR) {
        // The divergence, stated as an assertion rather than a comment: the
        // prefix is the reference's, the tail is this runtime's decoder.
        expect(expected.error).toMatch(/^Invalid header string: /);
        expect((thrown as JwtError).message).toMatch(/^Invalid header string: /);
        expect((thrown as JwtError).message).not.toBe(expected.error);
        return;
      }
      expect((thrown as JwtError).message).toBe(expected.error);
    });
  }
});

describe("reading an Authorization header", () => {
  for (const record of CORPUS.bearer_headers) {
    it(`reads ${JSON.stringify(record.header)} as ${JSON.stringify(record.token)}`, () => {
      expect(extractBearerToken(headers({ authorization: record.header })) ?? null).toBe(record.token);
    });
  }

  it("is nothing at all when there is no header", () => {
    expect(extractBearerToken(headers({}))).toBeUndefined();
  });
});

describe("minting a token", () => {
  it("reproduces the reference's own bytes for the token it announced", () => {
    // The corpus's first vector is exactly what setup_dev_idp mints. An
    // encoder that put the header's keys in the other order, or a space after
    // a colon, would produce a different string here.
    const minted = encodeJwt(
      {
        sub: "dev-user",
        iss: CORPUS.issuer,
        aud: CORPUS.audience,
        iat: CORPUS.past_exp,
        exp: CORPUS.future_exp,
        roles: ["admin"],
      },
      CORPUS.secret,
    );
    expect(minted).toBe(CORPUS.vectors[0]?.token);
  });

  it("mints something its own verifier accepts", () => {
    const token = encodeJwt(
      { sub: "someone", iss: CORPUS.issuer, aud: CORPUS.audience, exp: CORPUS.future_exp },
      CORPUS.secret,
    );
    expect(principalFromJwtToken(token, SETTINGS, () => CORPUS.past_exp).subject_id).toBe("someone");
  });
});

describe("the shapes only a hand-built token has", () => {
  const now = () => (CORPUS.past_exp + CORPUS.future_exp) / 2;

  it("covers every edge vector, so a corpus that shrank is visible", () => {
    expect(CORPUS.edge_vectors.length).toBe(21);
  });

  for (const vector of CORPUS.edge_vectors) {
    const settings = { ...SETTINGS, ...(vector.settings ?? {}) };
    if (vector.result.accepted) {
      const expected = vector.result;
      it(`accepts ${vector.name}: ${vector.why}`, () => {
        const principal = principalFromJwtToken(vector.token, settings, now);
        expect(principal.subject_id).toBe(expected.subject_id);
        expect([...principal.roles].sort()).toEqual(expected.roles);
        expect([...principal.scopes].sort()).toEqual(expected.scopes);
      });
      continue;
    }
    const expected = vector.result;
    it(`refuses ${vector.name}: ${vector.why}`, () => {
      let thrown: unknown;
      try {
        principalFromJwtToken(vector.token, settings, now);
      } catch (error) {
        thrown = error;
      }
      expect(thrown).toBeInstanceOf(JwtError);
      expect((thrown as JwtError).code).toBe(expected.error_type);
      expect((thrown as JwtError).message).toBe(expected.error);
    });
  }

  it("refuses an asymmetric algorithm even against a key shaped like a public one", () => {
    // The corpus reaches this with a shared secret, which is what a dev_token
    // deployment has. RS256 against a real PEM is not implemented by this port
    // either, and must fail closed rather than pass unverified.
    const header = Buffer.from(JSON.stringify({ alg: "RS256", typ: "JWT" }), "utf8").toString("base64url");
    const token = `${header}.${Buffer.from("{}", "utf8").toString("base64url")}.AAAA`;
    const settings = {
      ...SETTINGS,
      jwt_algorithms: ["RS256"],
      jwt_public_key_pem: "-----BEGIN PUBLIC KEY-----\nAAAA\n-----END PUBLIC KEY-----",
    };
    expect(() => principalFromJwtToken(token, settings, now)).toThrow(JwtError);
  });
});

describe("the decoder underneath, where a claim may go unchecked", () => {
  it("covers every decode vector", () => {
    expect(CORPUS.decode_vectors.length).toBe(7);
  });

  for (const vector of CORPUS.decode_vectors) {
    const options = {
      key: CORPUS.secret,
      algorithms: vector.args.algorithms,
      issuer: vector.args.issuer ?? undefined,
      audience: vector.args.audience ?? undefined,
      leeway: vector.args.leeway,
      require: vector.args.require ?? ["sub", "exp"],
      now: () => vector.args.now ?? CORPUS.past_exp,
    };
    if (vector.result.accepted) {
      const expected = vector.result;
      it(`accepts ${vector.name}: ${vector.why}`, () => {
        expect(decodeJwt(vector.token, options)).toEqual(expected.claims);
      });
      continue;
    }
    const expected = vector.result;
    it(`refuses ${vector.name}: ${vector.why}`, () => {
      let thrown: unknown;
      try {
        decodeJwt(vector.token, options);
      } catch (error) {
        thrown = error;
      }
      expect((thrown as JwtError).code).toBe(expected.error_type);
      expect((thrown as JwtError).message).toBe(expected.error);
    });
  }

  it("verifies against the runtime clock when nobody supplies one", () => {
    // No `now`: the only clock that can accept a token expiring in an hour is
    // the real one.
    const soon = Math.trunc(Date.now() / 1000) + 3600;
    const token = encodeJwt({ sub: "s", exp: soon }, CORPUS.secret);
    expect(decodeJwt(token, { key: CORPUS.secret, algorithms: ["HS256"] }).sub).toBe("s");
  });

  it("requires nothing and checks no clock when it is given no options at all", () => {
    const token = encodeJwt({ sub: "s" }, CORPUS.secret);
    expect(decodeJwt(token, { key: CORPUS.secret, algorithms: ["HS256"] })).toEqual({ sub: "s" });
  });
});

describe("resolving a principal from a request", () => {
  const now = () => CORPUS.past_exp;

  it("is anonymous when no credential was presented", () => {
    expect(resolveJwtPrincipal(headers({}), SETTINGS, now)).toEqual(anonymousPrincipal());
  });

  it("is anonymous, identically, when the credential does not verify", () => {
    // Byte-identical to the line above on purpose: a caller must not be able
    // to tell a forged token from no token by what came back.
    const forged = headers({ authorization: "Bearer not.a.real.token" });
    expect(resolveJwtPrincipal(forged, SETTINGS, now)).toEqual(resolveJwtPrincipal(headers({}), SETTINGS, now));
  });

  it("is the token's subject when it verifies", () => {
    const token = CORPUS.vectors[0]?.token as string;
    expect(resolveJwtPrincipal(headers({ authorization: `Bearer ${token}` }), SETTINGS, now).subject_id).toBe(
      "dev-user",
    );
  });

  it("gives an anonymous caller the least privilege rather than none", () => {
    // An empty role set would read as "unrestricted" to anything that tests
    // membership by exclusion.
    expect([...anonymousPrincipal().roles]).toEqual(["viewer"]);
  });
});
