#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Generate the tunnel wire-parity golden from the REAL Python protocol
(provide.uterm.tunnel.protocol). Run from the repo root:

    uv run python packages/provide-uterm-go/tunnelclient/testdata/gen_frames_golden.py

Writes frames_golden.json next to this script. The Go tunnelclient must encode
identical bytes for every case, so a framing change on either side fails CI.

The corpus header used to credit a `scratchpad/gen_golden.py` that was never
committed, which is why .ci/check_goldens.sh could not drift-check it. This
replaces that reference with a script that actually exists.

Payloads are held as bytes and emitted base64 so the wire bytes survive JSON
round-tripping — the whole point is byte parity, and any lossy text encoding in
the corpus would hide exactly the bugs it exists to catch.
"""

from __future__ import annotations

import base64
import json
import pathlib

from provide.uterm.tunnel.protocol import (
    CHANNEL_CONTROL,
    CHANNEL_DATA,
    CHANNEL_HTTP,
    CHANNEL_TCP,
    FLAG_DATA,
    FLAG_EOF,
    encode_control,
    encode_frame,
)

NOTE = (
    "Generated by packages/provide-uterm-go/tunnelclient/testdata/gen_frames_golden.py "
    "from provide.uterm.tunnel.protocol. Byte-for-byte wire parity corpus for Go tunnelclient."
)

# (channel, flags, payload). Spans: ordinary data, EOF with an empty payload on
# each stream channel, every byte value 0x00-0xff (the framing must be
# transparent, not text), a control-channel payload, a channel/flag pair outside
# the named constants (nothing may clamp them), and multi-byte UTF-8 including
# an astral emoji.
FRAMES: list[tuple[int, int, bytes]] = [
    (CHANNEL_DATA, FLAG_DATA, b"hello world"),
    (CHANNEL_DATA, FLAG_EOF, b""),
    (CHANNEL_TCP, FLAG_DATA, bytes(range(256))),
    (CHANNEL_TCP, FLAG_EOF, b""),
    (CHANNEL_HTTP, FLAG_DATA, b'{"type":"http_req"}'),
    (CHANNEL_CONTROL, FLAG_DATA, b"\x00\x01\x02\xff\xfe"),
    (42, 0x80, b"custom-channel-and-flags"),
    (CHANNEL_DATA, FLAG_DATA, "unicode: é中文 😀".encode()),
]

# (metadata, control message). The metadata is what the Go test reads to know
# which call it is checking; the message is what actually gets encoded.
CONTROLS: list[tuple[dict[str, object], dict[str, object]]] = [
    (
        {"kind": "open_terminal", "cols": 80, "rows": 24},
        {"type": "open", "channel": CHANNEL_DATA, "tunnel_type": "terminal", "term_size": [80, 24]},
    ),
    (
        {"kind": "resize", "cols": 100, "rows": 40},
        {"type": "resize", "channel": CHANNEL_DATA, "cols": 100, "rows": 40},
    ),
    (
        {"kind": "open_tcp", "port": 8080},
        {"type": "open", "channel": CHANNEL_TCP, "tunnel_type": "tcp", "local_port": 8080},
    ),
    (
        {"kind": "open_http", "port": 3000},
        {"type": "open", "channel": CHANNEL_HTTP, "tunnel_type": "http", "local_port": 3000},
    ),
]


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def build() -> dict[str, object]:
    return {
        "_note": NOTE,
        "channels": {
            "control": CHANNEL_CONTROL,
            "data": CHANNEL_DATA,
            "tcp": CHANNEL_TCP,
            "http": CHANNEL_HTTP,
        },
        "flags": {"data": FLAG_DATA, "eof": FLAG_EOF},
        "frames": [
            {
                "channel": channel,
                "flags": flags,
                "payload_b64": b64(payload),
                "frame_b64": b64(encode_frame(channel, payload, flags=flags)),
            }
            for channel, flags, payload in FRAMES
        ],
        "controls": [{**meta, "frame_b64": b64(encode_control(msg))} for meta, msg in CONTROLS],
    }


def main() -> None:
    corpus = build()
    out = pathlib.Path(__file__).with_name("frames_golden.json")
    out.write_text(json.dumps(corpus, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(corpus['frames'])} frames, {len(corpus['controls'])} controls)")


if __name__ == "__main__":
    main()
