#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Prove first-party uterm VNC console path: lab + server + binary /gui/vnc.

Live path (not mocked):
  1. Ensure ``uterm-test-vnc`` lab image/container (plain :5900, TLS :5901)
  2. Start ``uterm server`` with lab ``[[graphical_targets]]``
  3. Wait for auto-started shell worker; REST acquire as operator
  4. Open binary WebSocket to ``/worker/…/hijack/…/gui/vnc?target_id=…``
  5. Complete RFB ProtocolVersion exchange **through the relay**
  6. Repeat plain path twice; once for TLS; once denied path
  7. Optionally open the baked ``vnc.html`` page and screenshot

Usage (repo root)::

    uv run python scripts/prove_uterm_vnc_console.py
    uv run python scripts/prove_uterm_vnc_console.py --evidence-dir /path --runs 2
    SCRATCH=/path uv run python scripts/prove_uterm_vnc_console.py

Exit 0 only when every required observation succeeds.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

# Reuse lab helpers from the sibling proof module (real entry points).
_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import prove_vnc_lab as vnc_lab  # noqa: E402

IMAGE_NAME = vnc_lab.IMAGE_NAME
LAB_CONTAINER = "uterm-test-vnc-console-prove"
SERVER_SESSION = "vnc-shell"
TARGET_PLAIN = "lab-vnc-plain"
TARGET_TLS = "lab-vnc-tls"
ADMIN_HEADERS = {
    "x-uterm-principal": "alice",
    "x-uterm-role": "admin",
    "x-uterm-tenant": "lab",
    "Content-Type": "application/json",
}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _evidence_dir(explicit: str | None) -> Path:
    for key in (explicit, os.environ.get("EVIDENCE_DIR"), os.environ.get("SCRATCH")):
        if key:
            p = Path(key)
            p.mkdir(parents=True, exist_ok=True)
            return p
    p = Path(os.environ.get("TMPDIR", "/tmp")) / "uterm-vnc-console-prove"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def write_server_config(
    path: Path,
    *,
    host: str,
    port: int,
    plain_port: int,
    tls_port: int,
    token: str,
) -> None:
    """Write a lab server TOML with graphical targets pointing at the live lab ports."""
    body = f"""\
# Auto-generated by prove_uterm_vnc_console.py — do not commit.
[server]
host = "{host}"
port = {port}
public_base_url = "http://{host}:{port}"
title = "uterm-vnc-console-prove"

[auth]
mode = "header"
header_mode_acknowledged = true
principal_header = "x-uterm-principal"
role_header = "x-uterm-role"
worker_bearer_token = "{token}"

[ui]
app_path = "/app"
assets_path = "/_terminal"

[recording]
enabled_by_default = false
directory = "{path.parent / "recordings"}"

[security]
block_private_connector_targets = false

[[sessions]]
session_id = "{SERVER_SESSION}"
display_name = "VNC lab shell"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["vnc-lab"]

[[graphical_targets]]
target_id = "{TARGET_PLAIN}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{plain_port}"
name = "VNC Lab Plain"
enabled = true

[[graphical_targets]]
target_id = "{TARGET_TLS}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{tls_port}"
name = "VNC Lab TLS"
enabled = true

[graphical_targets.config]
tls = true
tls_insecure = true
"""
    _write(path, body)


def start_server(*, root: Path, config: Path, log_path: Path) -> subprocess.Popen[str]:
    """Start ``uterm server``; return the Popen handle."""
    cmd = [
        sys.executable,
        "-m",
        "provide.uterm.cli",
        "server",
        "--config",
        str(config),
    ]
    # Prefer the installed console script when present.
    which = subprocess.run(["which", "uterm"], capture_output=True, text=True, check=False)
    if which.returncode == 0 and which.stdout.strip():
        cmd = [which.stdout.strip(), "server", "--config", str(config)]

    log_f = log_path.open("w", encoding="utf-8")
    log_f.write(f"$ {' '.join(cmd)}\n")
    log_f.flush()
    proc = subprocess.Popen(
        cmd,
        cwd=str(root),
        stdout=log_f,
        stderr=subprocess.STDOUT,
        text=True,
        env={**os.environ, "UTERM_API_ONLY": "0"},
    )
    # Stash log handle on the proc for cleanup.
    proc._log_f = log_f  # type: ignore[attr-defined]
    return proc


def wait_http(url: str, *, timeout: float = 30.0) -> None:
    deadline = time.time() + timeout
    last: Exception | None = None
    while time.time() < deadline:
        try:
            req = urllib.request.Request(url, headers=ADMIN_HEADERS)  # noqa: S310
            with urllib.request.urlopen(req, timeout=2) as resp:  # noqa: S310
                if resp.status < 500:
                    return
        except Exception as exc:
            last = exc
            time.sleep(0.25)
    raise RuntimeError(f"server not ready at {url}: {last}")


def http_json(method: str, url: str, *, headers: dict[str, str], body: dict | None = None) -> tuple[int, object]:
    data = None if body is None else json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers, method=method)  # noqa: S310
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310
            raw = resp.read().decode("utf-8")
            return resp.status, json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        try:
            parsed: object = json.loads(raw) if raw else {}
        except json.JSONDecodeError:
            parsed = raw
        return exc.code, parsed


def wait_worker_and_acquire(base: str, *, timeout: float = 45.0) -> str:
    """Poll until shell worker is up, then REST acquire; return hijack_id."""
    deadline = time.time() + timeout
    last_err = "no attempt"
    while time.time() < deadline:
        status, payload = http_json(
            "POST",
            f"{base}/worker/{SERVER_SESSION}/hijack/acquire",
            headers=ADMIN_HEADERS,
            body={"owner": "alice", "lease_s": 120},
        )
        if status == 200 and isinstance(payload, dict) and payload.get("hijack_id"):
            return str(payload["hijack_id"])
        last_err = f"status={status} body={payload!r}"
        time.sleep(0.5)
    raise RuntimeError(f"hijack acquire failed: {last_err}")


def rfb_through_relay(
    base_ws: str,
    *,
    worker_id: str,
    hijack_id: str,
    target_id: str,
    headers: dict[str, str],
    timeout: float = 10.0,
) -> str:
    """Open binary WS to /gui/vnc and complete RFB version exchange via the relay.

    Uses the ``websockets`` library (already a project dependency).
    """
    import asyncio

    from websockets.asyncio.client import connect

    path = f"/worker/{worker_id}/hijack/{hijack_id}/gui/vnc?target_id={target_id}"
    url = base_ws + path
    # websockets expects a list of (name, value) for additional_headers in newer APIs.
    extra = [(k, v) for k, v in headers.items() if k.lower() != "content-type"]

    async def _run() -> str:
        lines = [f"ws_url={url}", f"target_id={target_id}"]
        async with connect(
            url,
            additional_headers=extra,
            open_timeout=timeout,
            close_timeout=5,
            max_size=2**22,
        ) as ws:
            lines.append("ws_open=ok")
            # Upstream VNC → relay → us: expect RFB ProtocolVersion (12 bytes).
            server_version = await asyncio.wait_for(ws.recv(), timeout=timeout)
            if isinstance(server_version, str):
                server_version = server_version.encode("latin-1")
            lines.append(f"server_protocol_version={server_version!r}")
            if len(server_version) != 12 or not server_version.startswith(b"RFB "):
                raise RuntimeError(f"invalid RFB ProtocolVersion through relay: {server_version!r}")
            # Echo version (client choice).
            await ws.send(server_version)
            lines.append(f"client_protocol_version={server_version!r}")
            # Security types (RFB 3.7/3.8): U8 count + types
            n_raw = await asyncio.wait_for(ws.recv(), timeout=timeout)
            if isinstance(n_raw, str):
                n_raw = n_raw.encode("latin-1")
            if not n_raw:
                raise RuntimeError("empty security handshake from upstream")
            n_types = n_raw[0]
            rest = n_raw[1:]
            while len(rest) < n_types:
                more = await asyncio.wait_for(ws.recv(), timeout=timeout)
                if isinstance(more, str):
                    more = more.encode("latin-1")
                rest += more
            types = rest[:n_types]
            lines.append(f"security_types={list(types)}")
            if 1 not in types:
                raise RuntimeError(f"expected Security None (1); got {list(types)}")
            await ws.send(bytes([1]))
            # Optional SecurityResult
            try:
                result = await asyncio.wait_for(ws.recv(), timeout=2.0)
                if isinstance(result, str):
                    result = result.encode("latin-1")
                lines.append(f"security_result={result!r}")
            except TimeoutError:
                lines.append("security_result=<timeout-ok>")
            lines.append("rfb_handshake=ok")
            lines.append("relay_path=ok")
        return "\n".join(lines) + "\n"

    return asyncio.run(_run())


def denied_path_probe(base_ws: str, *, worker_id: str, hijack_id: str) -> str:
    """Viewer-only principal must get close 1008."""
    import asyncio

    from websockets.asyncio.client import connect
    from websockets.exceptions import ConnectionClosed

    path = f"/worker/{worker_id}/hijack/{hijack_id}/gui/vnc?target_id={TARGET_PLAIN}"
    url = base_ws + path
    headers = [
        ("x-uterm-principal", "viewer-bob"),
        ("x-uterm-role", "viewer"),
        ("x-uterm-tenant", "lab"),
    ]

    async def _run() -> str:
        lines = [f"ws_url={url}", "principal=viewer"]
        try:
            async with connect(url, additional_headers=headers, open_timeout=10, close_timeout=5) as ws:
                try:
                    await asyncio.wait_for(ws.recv(), timeout=5)
                    lines.append("unexpected_message=true")
                except ConnectionClosed as exc:
                    lines.append(f"close_code={exc.code}")
                    lines.append(f"close_reason={exc.reason!r}")
                    if exc.code != 1008:
                        raise RuntimeError(f"expected 1008, got {exc.code}") from exc
                    lines.append("denied=ok")
                    return "\n".join(lines) + "\n"
                # Some stacks close without a message.
                await ws.close()
                lines.append("closed_without_code")
        except ConnectionClosed as exc:
            lines.append(f"close_code={exc.code}")
            lines.append(f"close_reason={exc.reason!r}")
            if exc.code != 1008:
                raise RuntimeError(f"expected 1008, got {exc.code}") from exc
            lines.append("denied=ok")
            return "\n".join(lines) + "\n"
        raise RuntimeError("viewer was not denied")

    return asyncio.run(_run())


def missing_target_probe(base_ws: str, *, worker_id: str, hijack_id: str) -> str:
    """Bad target_id → 1013 upstream unavailable."""
    import asyncio

    from websockets.asyncio.client import connect
    from websockets.exceptions import ConnectionClosed

    path = f"/worker/{worker_id}/hijack/{hijack_id}/gui/vnc?target_id=does-not-exist"
    url = base_ws + path
    headers = list(ADMIN_HEADERS.items())

    async def _run() -> str:
        lines = [f"ws_url={url}", "target_id=does-not-exist"]
        try:
            async with connect(url, additional_headers=headers, open_timeout=10, close_timeout=5) as ws:
                try:
                    await asyncio.wait_for(ws.recv(), timeout=5)
                except ConnectionClosed as exc:
                    lines.append(f"close_code={exc.code}")
                    if exc.code != 1013:
                        raise RuntimeError(f"expected 1013, got {exc.code}") from exc
                    lines.append("upstream_unavailable=ok")
                    return "\n".join(lines) + "\n"
                await ws.close()
        except ConnectionClosed as exc:
            lines.append(f"close_code={exc.code}")
            if exc.code != 1013:
                raise RuntimeError(f"expected 1013, got {exc.code}") from exc
            lines.append("upstream_unavailable=ok")
            return "\n".join(lines) + "\n"
        raise RuntimeError("missing target did not close with 1013")

    return asyncio.run(_run())


def try_screenshot(
    *,
    base_http: str,
    hijack_id: str,
    evidence: Path,
) -> str:
    """Best-effort Playwright screenshot of the uterm VNC page."""
    url = f"{base_http}/_terminal/vnc.html?worker_id={SERVER_SESSION}&hijack_id={hijack_id}&target_id={TARGET_PLAIN}"
    out = evidence / "uterm-vnc-console.png"
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        msg = f"playwright unavailable: {exc}\npage_url={url}\n"
        _write(evidence / "browser-unavailable.log", msg)
        return msg

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            # Browsers cannot set custom headers on JS WebSocket; header-mode
            # auth also accepts cookies (uterm_principal / uterm_role).
            context = browser.new_context(
                extra_http_headers={
                    "x-uterm-principal": "alice",
                    "x-uterm-role": "admin",
                    "x-uterm-tenant": "lab",
                }
            )
            # Parse base for cookie domain.
            from urllib.parse import urlparse

            parsed = urlparse(base_http)
            cookie_domain = parsed.hostname or "127.0.0.1"
            context.add_cookies(
                [
                    {
                        "name": "uterm_principal",
                        "value": "alice",
                        "domain": cookie_domain,
                        "path": "/",
                    },
                    {
                        "name": "uterm_role",
                        "value": "admin",
                        "domain": cookie_domain,
                        "path": "/",
                    },
                    {
                        "name": "uterm_tenant",
                        "value": "lab",
                        "domain": cookie_domain,
                        "path": "/",
                    },
                ]
            )
            page = context.new_page()
            page.goto(url, wait_until="domcontentloaded", timeout=30_000)
            # Wait for Connected status or give RFB handshake time.
            try:
                page.wait_for_function(
                    """() => {
                      const el = document.getElementById('vnc-status');
                      return el && (el.dataset.state === 'connected'
                        || el.dataset.state === 'denied'
                        || el.dataset.state === 'error'
                        || el.dataset.state === 'unavailable');
                    }""",
                    timeout=15_000,
                )
            except Exception:
                page.wait_for_timeout(3000)
            # Allow framebuffer updates after RFB connect before snapshot.
            page.wait_for_timeout(2500)
            status = page.evaluate(
                """() => {
                  const el = document.getElementById('vnc-status');
                  const canvas = document.querySelector('#vnc-screen canvas');
                  return {
                    state: el ? el.dataset.state : null,
                    text: el ? el.textContent : null,
                    canvas_w: canvas ? canvas.width : 0,
                    canvas_h: canvas ? canvas.height : 0,
                  };
                }"""
            )
            page.screenshot(path=str(out), full_page=True)
            browser.close()
        return f"screenshot=ok path={out}\npage_url={url}\nstatus={status!r}\n"
    except Exception as exc:
        msg = f"screenshot failed: {exc}\npage_url={url}\n"
        _write(evidence / "browser-unavailable.log", msg)
        return msg


def stop_server(proc: subprocess.Popen[str]) -> None:
    if proc.poll() is not None:
        return
    proc.send_signal(signal.SIGTERM)
    try:
        proc.wait(timeout=10)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=5)
    log_f = getattr(proc, "_log_f", None)
    if log_f is not None:
        log_f.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", default=None)
    parser.add_argument("--runs", type=int, default=2, help="plain RFB relay runs (default 2)")
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--skip-screenshot", action="store_true")
    args = parser.parse_args(argv)

    evidence = _evidence_dir(args.evidence_dir)
    root = _repo_root()
    lines: list[str] = [f"evidence={evidence}", f"root={root}"]

    if not vnc_lab._docker_available():
        msg = "docker not available\n"
        _write(evidence / "docker-unavailable.log", msg)
        print(msg, file=sys.stderr)
        return 2

    # --- lab ---
    if not args.skip_build:
        vnc_lab.build_image(root=root, log_path=evidence / "lab-image-build.log")
    plain_port, tls_port = vnc_lab.start_container(name=LAB_CONTAINER, demo_url="https://example.com")
    lines.append(f"lab_plain_port={plain_port}")
    lines.append(f"lab_tls_port={tls_port}")
    vnc_lab.wait_rfb("127.0.0.1", plain_port, retries=60, delay=0.5)
    lines.append("lab_plain_ready=ok")

    # --- server ---
    host = "127.0.0.1"
    port = _free_port()
    token = "vnc-lab-worker-bearer-token-32chars"  # noqa: S105 — lab fixture only
    cfg_path = evidence / "server.toml"
    write_server_config(
        cfg_path,
        host=host,
        port=port,
        plain_port=plain_port,
        tls_port=tls_port,
        token=token,
    )
    server_log = evidence / "server.log"
    proc = start_server(root=root, config=cfg_path, log_path=server_log)
    base = f"http://{host}:{port}"
    base_ws = f"ws://{host}:{port}"
    try:
        wait_http(f"{base}/readyz", timeout=45.0)
        lines.append(f"server_ready={base}")

        # Structural: VNC page served
        req = urllib.request.Request(f"{base}/_terminal/vnc.html", headers=ADMIN_HEADERS)  # noqa: S310
        with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310
            html = resp.read().decode("utf-8", errors="replace")
        if "vnc-screen" not in html:
            raise RuntimeError("vnc.html missing vnc-screen marker")
        lines.append("vnc_html=ok")

        hijack_id = wait_worker_and_acquire(base)
        lines.append(f"hijack_id={hijack_id}")

        # Plain path — N runs
        for i in range(1, max(1, args.runs) + 1):
            log_name = "vnc-console-connect.log" if i == 1 else f"vnc-console-connect-{i}.log"
            # plan names: connect.log and connect-2.log
            if i == 2:
                log_name = "vnc-console-connect-2.log"
            summary = rfb_through_relay(
                base_ws,
                worker_id=SERVER_SESSION,
                hijack_id=hijack_id,
                target_id=TARGET_PLAIN,
                headers=ADMIN_HEADERS,
            )
            _write(evidence / log_name, summary)
            if "rfb_handshake=ok" not in summary:
                raise RuntimeError(f"plain run {i} failed RFB handshake")
            lines.append(f"plain_run_{i}=ok")

        # TLS path
        tls_summary = rfb_through_relay(
            base_ws,
            worker_id=SERVER_SESSION,
            hijack_id=hijack_id,
            target_id=TARGET_TLS,
            headers=ADMIN_HEADERS,
        )
        _write(evidence / "vnc-console-tls.log", tls_summary)
        if "rfb_handshake=ok" not in tls_summary:
            raise RuntimeError("TLS relay RFB handshake failed")
        lines.append("tls_run=ok")

        # Denied
        denied = denied_path_probe(base_ws, worker_id=SERVER_SESSION, hijack_id=hijack_id)
        missing = missing_target_probe(base_ws, worker_id=SERVER_SESSION, hijack_id=hijack_id)
        _write(evidence / "vnc-console-denied.log", denied + "\n" + missing)
        lines.append("denied=ok")

        if not args.skip_screenshot:
            shot = try_screenshot(base_http=base, hijack_id=hijack_id, evidence=evidence)
            _write(evidence / "screenshot-attempt.log", shot)
            lines.append("screenshot_attempt=done")

        summary = "\n".join(lines) + "\nprove=ok\n"
        _write(evidence / "prove-summary.log", summary)
        print(summary)
        return 0
    except Exception as exc:
        err = "\n".join(lines) + f"\nerror={exc}\n"
        _write(evidence / "prove-error.log", err)
        print(err, file=sys.stderr)
        return 1
    finally:
        stop_server(proc)
        vnc_lab._remove_container(LAB_CONTAINER)


if __name__ == "__main__":
    raise SystemExit(main())
