#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Record video: first-party uterm VNC console showing lab browser on text demos.

End-to-end proof (not mocked)::

  1. Start uterm server (shell demo session + RFB graphical targets)
  2. Start uterm-test-vnc lab with Chromium pointed at the host's
     ``/_terminal/terminal.html`` text console (and a second tab/window path)
  3. Drive live shell output (text-based demos) into the session
  4. Open host Playwright on first-party ``vnc.html`` and record webm + stills

Usage (repo root)::

    uv run python scripts/record_uterm_vnc_demo_video.py
    uv run python scripts/record_uterm_vnc_demo_video.py --seconds 18 --skip-build
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import prove_uterm_vnc_console as prove  # noqa: E402
import prove_vnc_lab as vnc_lab  # noqa: E402

LAB = "uterm-vnc-demo-video"
SHELL_SESSION = "provide-shell"
VNC_WORKER = prove.SERVER_SESSION
TARGET = prove.TARGET_PLAIN
LAB_WORKER_TOKEN = "vnc-lab-worker-bearer-token-32chars"  # noqa: S105 — lab fixture

# Host gateway seen from Docker Desktop / Colima / Linux docker0.
_HOST_FROM_DOCKER = "host.docker.internal"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _evidence_dir(explicit: str | None) -> Path:
    for key in (explicit, os.environ.get("EVIDENCE_DIR"), os.environ.get("SCRATCH")):
        if key:
            p = Path(key)
            p.mkdir(parents=True, exist_ok=True)
            return p
    p = _repo_root() / "demo" / "vnc-lab"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("0.0.0.0", 0))
        return int(s.getsockname()[1])


def write_demo_server_config(
    path: Path,
    *,
    host: str,
    port: int,
    plain_port: int,
    tls_port: int,
) -> None:
    """Server config: text shell demo + VNC lab targets; bind all interfaces."""
    body = f"""\
# Auto-generated by record_uterm_vnc_demo_video.py — do not commit.
[server]
host = "{host}"
port = {port}
public_base_url = "http://127.0.0.1:{port}"
title = "uterm VNC + text demos"

[auth]
mode = "header"
header_mode_acknowledged = true
principal_header = "x-uterm-principal"
role_header = "x-uterm-role"
worker_bearer_token = "{LAB_WORKER_TOKEN}"
# Non-loopback bind requires an allowlist; local recorder + Docker Desktop peers.
trusted_proxy_ips = [
  "127.0.0.1",
  "::1",
  "192.168.5.1",
  "192.168.5.2",
  "192.168.65.1",
  "192.168.65.2",
  "172.17.0.1",
  "172.18.0.1",
  "10.0.0.1",
]

[ui]
app_path = "/app"
assets_path = "/_terminal"

[recording]
enabled_by_default = false
directory = "{path.parent / "recordings"}"

[security]
block_private_connector_targets = false

# Text-based shell demo the lab Chromium will open.
# hijack mode so the recorder can inject live demo keystrokes via REST.
[[sessions]]
session_id = "{SHELL_SESSION}"
display_name = "Provide Shell Demo"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["demo", "text"]

# Second shell so the demo can flip between sessions.
[[sessions]]
session_id = "demo-shell-2"
display_name = "Demo Shell Two"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["demo", "text"]
# Worker used only for VNC hijack lease (authz gate for /gui/vnc).
[[sessions]]
session_id = "{VNC_WORKER}"
display_name = "VNC lease shell"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["vnc-lab"]

[[graphical_targets]]
target_id = "{TARGET}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{plain_port}"
name = "VNC Lab Plain"
enabled = true
width = 1280
height = 720

[[graphical_targets]]
target_id = "{prove.TARGET_TLS}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{tls_port}"
name = "VNC Lab TLS"
enabled = true

[graphical_targets.config]
tls = true
tls_insecure = true
"""
    path.write_text(body, encoding="utf-8")


# Fixed host ports so the uterm server can start *before* the lab (Chromium
# must open the text demo URL on first launch — mid-run browser kill is flaky).
LAB_HOST_PLAIN = 25900
LAB_HOST_TLS = 25901


def start_lab_with_demo_url(
    *,
    name: str,
    demo_url: str,
    host_plain: int = LAB_HOST_PLAIN,
    host_tls: int = LAB_HOST_TLS,
) -> tuple[int, int]:
    """Start lab container; Chromium opens *demo_url* (host uterm text console)."""
    vnc_lab._remove_container(name)
    result = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            name,
            "--shm-size",
            vnc_lab.DEFAULT_SHM,
            "--add-host=host.docker.internal:host-gateway",
            "-p",
            f"{host_plain}:{vnc_lab.RFB_PLAIN_PORT}",
            "-p",
            f"{host_tls}:{vnc_lab.RFB_SSL_PORT}",
            "-e",
            f"DEMO_URL={demo_url}",
            vnc_lab.IMAGE_NAME,
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"docker run failed: {result.stderr.strip()[:500]}")
    return host_plain, host_tls


def lab_chrome_args(name: str) -> str:
    """Return lab Chromium command lines (for verifying DEMO_URL stuck)."""
    result = subprocess.run(
        ["docker", "exec", name, "bash", "-lc", "ps -C chromium -o args= 2>/dev/null | tr '\\n' '|'"],
        capture_output=True,
        text=True,
        timeout=15,
        check=False,
    )
    return (result.stdout or "").strip()


def http_json(method: str, url: str, *, headers: dict[str, str], body: dict | None = None) -> tuple[int, object]:
    data = None if body is None else json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers, method=method)  # noqa: S310
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310
            raw = resp.read().decode("utf-8")
            return resp.status, json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        try:
            parsed: object = json.loads(raw) if raw else {}
        except json.JSONDecodeError:
            parsed = raw
        return exc.code, parsed


def acquire_shell(base: str, headers: dict[str, str], *, session: str = SHELL_SESSION) -> tuple[str | None, list[str]]:
    """Acquire a REST hijack lease on the reference shell session."""
    log: list[str] = []
    status, payload = http_json(
        "POST",
        f"{base}/worker/{session}/hijack/acquire",
        headers=headers,
        body={"owner": "demo-driver", "lease_s": 300},
    )
    if status != 200 or not isinstance(payload, dict):
        log.append(f"acquire_{session}=status_{status} body={payload!r}")
        return None, log
    hid = str(payload["hijack_id"])
    log.append(f"acquire_{session}={hid}")
    return hid, log


def send_shell_keys(
    base: str,
    headers: dict[str, str],
    hid: str,
    keys: str,
    *,
    session: str = SHELL_SESSION,
) -> tuple[int, object]:
    return http_json(
        "POST",
        f"{base}/worker/{session}/hijack/{hid}/send",
        headers=headers,
        body={"keys": keys, "timeout_ms": 1500},
    )


def seed_shell_banner(base: str, headers: dict[str, str], hid: str) -> list[str]:
    """Minimal seed so nested browser has *something* on first paint."""
    log: list[str] = []
    for cmd in (
        "/clear\r",
        "/nick demo\r",
        "/say provide-uterm · nested browser demo starting…\r",
        "/say (live stream will paint below)\r",
    ):
        st, body = send_shell_keys(base, headers, hid, cmd)
        if st >= 400:
            log.append(f"seed_err={st} {body!r}")
        time.sleep(0.08)
    log.append("seed_ok")
    return log


# Website-demo pacing: fire several keystrokes quickly, then a short hold so
# the nested browser visibly advances through the full script in ~8-12s total
# (not one line every 2s with multi-second RFB reconnects).
#
# Each chapter is a burst of /say lines; the recorder waits once per chapter.
LIVE_DEMO_CHAPTERS: list[list[str]] = [
    [
        "/clear\r",
        "/nick demo\r",
        "/say ════════════════════════════════════════\r",
        "/say   provide-uterm · text-based shell demo\r",
        "/say ════════════════════════════════════════\r",
    ],
    [
        "/say [1/6] whoami → demo operator\r",
        "/say [2/6] pwd    → hosted connector\r",
        "/say [3/6] RAINBOW shell output · fan-out\r",
    ],
    [
        "/status\r",
        "/shell\r",
        "/say [4/6] nested Chromium via /ws/browser\r",
    ],
    [
        "/say [5/6] RFB relay · snapshot fan-out\r",
        "plain chat: host.docker.internal → lab\r",
        "/say [6/6] >>> watching this shell via VNC <<<\r",
        "/say ready · demo complete\r",
    ],
]

# Per-keystroke delay inside a chapter (website-demo typing pace).
_KEY_GAP_S = 0.08
# Hold after a chapter so nested xterm + x11vnc can paint (no RFB reconnect).
_CHAPTER_HOLD_S = 0.9


def nudge_lab_desktop(lab_name: str = LAB) -> None:
    """Force X damage on the lab Chromium window without tearing the RFB session.

    Chromium canvas under Xvfb often skips incremental damage; a 1px resize
    makes x11vnc push a full frame so noVNC updates without connect/disconnect
    flashing.
    """
    script = r"""
set -e
W=1280; H=720
for pat in Chromium chromium Chrome chrome; do
  ids=$(xdotool search --onlyvisible --class "$pat" 2>/dev/null || true)
  for id in $ids; do
    xdotool windowsize "$id" $((W-1)) "$H" 2>/dev/null || true
    xdotool windowsize "$id" "$W" "$H" 2>/dev/null || true
    xdotool windowmove "$id" 0 0 2>/dev/null || true
    exit 0
  done
done
exit 0
"""
    try:
        subprocess.run(
            ["docker", "exec", lab_name, "bash", "-lc", script],
            capture_output=True,
            text=True,
            timeout=8,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        pass


def canvas_fingerprint(page: object) -> str:
    """Fingerprint the noVNC canvas (toDataURL — robust against partial damage)."""
    return str(
        page.evaluate(  # type: ignore[attr-defined]
            """() => {
              const c = document.querySelector('#vnc-screen canvas');
              if (!(c instanceof HTMLCanvasElement) || c.width < 8 || c.height < 8) return 'no-canvas';
              // Downscale via a scratch canvas so the hash stays small/fast.
              const w = 64, h = 36;
              const off = document.createElement('canvas');
              off.width = w; off.height = h;
              const octx = off.getContext('2d');
              if (!octx) return 'no-ctx';
              octx.drawImage(c, 0, 0, w, h);
              const data = octx.getImageData(0, 0, w, h).data;
              let sum = 0;
              for (let i = 0; i < data.length; i += 4) {
                sum = (sum * 33 + data[i] + data[i+1] * 3 + data[i+2] * 7) >>> 0;
              }
              // Also sample a few mid-frame pixels for quick diffs.
              const ctx = c.getContext('2d', { willReadFrequently: true });
              const samples = [];
              if (ctx) {
                for (const [fx, fy] of [[0.3,0.35],[0.5,0.45],[0.7,0.55],[0.4,0.65]]) {
                  const d = ctx.getImageData(Math.floor(c.width*fx), Math.floor(c.height*fy), 1, 1).data;
                  samples.push(`${d[0]},${d[1]},${d[2]}`);
                }
              }
              return `${c.width}x${c.height}:${sum.toString(16)}:${samples.join(';')}`;
            }"""
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", default=None)
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument(
        "--seconds",
        type=float,
        default=0.0,
        help="optional continuous tail clip after the storyboard (0 = storyboard only)",
    )
    args = parser.parse_args(argv)

    evidence = _evidence_dir(args.evidence_dir)
    root = _repo_root()
    shots = evidence / "screenshots"
    shots.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [f"evidence={evidence}"]

    if not vnc_lab._docker_available():
        (evidence / "docker-unavailable.log").write_text("docker missing\n", encoding="utf-8")
        return 2

    if not args.skip_build:
        vnc_lab.build_image(root=root, log_path=evidence / "lab-build.log")

    # --- Order matters: server first, then lab Chromium with DEMO_URL=text demo ---
    # Fixed RFB publish ports so graphical_targets are known before docker run.
    host_bind = "0.0.0.0"
    server_port = _free_port()
    plain_port, tls_port = LAB_HOST_PLAIN, LAB_HOST_TLS
    demo_url = (
        f"http://{_HOST_FROM_DOCKER}:{server_port}/_terminal/terminal.html?worker_id={SHELL_SESSION}&role=browser"
    )
    lines.append(f"demo_url={demo_url}")

    cfg = evidence / "server.toml"
    write_demo_server_config(
        cfg,
        host=host_bind,
        port=server_port,
        plain_port=plain_port,
        tls_port=tls_port,
    )

    # TEST_MODE so lab browser WS auth succeeds without cookies.
    env = {**os.environ, "UTERM_TEST_MODE": "1", "UTERM_API_ONLY": "0"}
    log_path = evidence / "server.log"
    cmd = [
        str(root / ".venv" / "bin" / "uterm"),
        "server",
        "--config",
        str(cfg),
    ]
    if not Path(cmd[0]).is_file():
        cmd = [sys.executable, "-m", "provide.uterm.cli", "server", "--config", str(cfg)]
    log_f = log_path.open("w", encoding="utf-8")
    log_f.write(f"$ {' '.join(cmd)}\nUTERM_TEST_MODE=1\n")
    log_f.flush()
    proc = subprocess.Popen(
        cmd,
        cwd=str(root),
        stdout=log_f,
        stderr=subprocess.STDOUT,
        text=True,
        env=env,
    )
    proc._log_f = log_f  # type: ignore[attr-defined]

    # UTERM_TEST_MODE mints WS principal subject_id="test-admin". REST acquires
    # must use the same subject so /gui/vnc lease ownership checks pass.
    headers = {
        "x-uterm-principal": "test-admin",
        "x-uterm-role": "admin",
        "x-uterm-tenant": "lab",
        "Content-Type": "application/json",
    }
    base = f"http://127.0.0.1:{server_port}"
    try:
        prove.wait_http(f"{base}/readyz", timeout=60.0)
        lines.append(f"server_ready={base}")

        # auto_start workers connect a beat after /readyz; wait until the
        # shell session reports connected before hijack/acquire.
        connected = False
        for _ in range(80):
            st, body = http_json("GET", f"{base}/api/sessions/{SHELL_SESSION}", headers=headers)
            if st == 200 and isinstance(body, dict) and body.get("connected"):
                connected = True
                break
            time.sleep(0.15)
        lines.append(f"shell_connected={connected}")
        if not connected:
            raise RuntimeError(f"session {SHELL_SESSION} never reached connected state")

        # Seed a short banner first (not the full demo) so nested terminal has
        # content on attach; progressive beats run *during* VNC recording.
        shell_hid, acq_log = acquire_shell(base, headers, session=SHELL_SESSION)
        lines.extend(acq_log)
        lines.append(f"shell_lease={shell_hid}")
        if not shell_hid:
            raise RuntimeError(f"failed to acquire shell lease: {acq_log}")
        lines.extend(seed_shell_banner(base, headers, shell_hid))
        time.sleep(0.4)

        # Lab Chromium opens the text terminal on *first* launch (no example.com).
        plain_port, tls_port = start_lab_with_demo_url(
            name=LAB,
            demo_url=demo_url,
            host_plain=LAB_HOST_PLAIN,
            host_tls=LAB_HOST_TLS,
        )
        lines.append(f"lab_plain={plain_port} lab_tls={tls_port}")
        vnc_lab.wait_rfb("127.0.0.1", plain_port, retries=80, delay=0.5)
        lines.append("lab_rfb=ok")

        # Wait for Chromium; assert it is on the text demo URL (not example.com).
        chrome_args = ""
        for _ in range(40):
            time.sleep(0.5)
            chrome_args = lab_chrome_args(LAB)
            if "terminal.html" in chrome_args or "provide-shell" in chrome_args:
                break
        lines.append(f"chrome_args={chrome_args[:500]!r}")
        if "terminal.html" not in chrome_args and "provide-shell" not in chrome_args:
            raise RuntimeError(
                "lab Chromium is not on the text demo URL "
                f"(expected terminal.html / provide-shell); args={chrome_args[:400]!r}"
            )
        lines.append("chrome_on_text_demo=ok")
        # Nested terminal: assets + WS + initial snapshot paint.
        time.sleep(2.0)

        # Prove host-side terminal.html paints (same assets the lab loads).
        # Do NOT set x-uterm-* as context-wide extra_http_headers: Playwright
        # attaches them to every request, including CDN xterm.js, and CDNs
        # reject the CORS preflight. UTERM_TEST_MODE already mints WS admin.
        from playwright.sync_api import sync_playwright as _sync_pw

        term_url = f"{base}/_terminal/terminal.html?worker_id={SHELL_SESSION}&role=browser"
        with _sync_pw() as _p:
            _b = _p.chromium.launch(headless=True)
            _c = _b.new_context()
            _pg = _c.new_page()
            _pg.goto(term_url, wait_until="domcontentloaded", timeout=30_000)
            _pg.wait_for_function(
                """() => {
                  const loading = document.querySelector('[id^="loadingScreen-"]');
                  if (!loading) return false;
                  if (loading.style.display !== 'none') return false;
                  const rows = document.querySelectorAll('.xterm-rows > div');
                  if (rows.length > 0) {
                    const t = Array.from(rows).map(r => r.textContent || '').join('\\n');
                    if (t.trim().length > 10) return true;
                  }
                  const term = window.demoTerminal;
                  if (term && typeof term.getBufferText === 'function') {
                    const b = term.getBufferText(80) || '';
                    return b.trim().length > 10;
                  }
                  return false;
                }""",
                timeout=25_000,
            )
            buf = _pg.evaluate(
                """() => {
                  const t = window.demoTerminal;
                  if (t && typeof t.getBufferText === 'function') {
                    const b = t.getBufferText(80);
                    if (b && b.trim()) return b;
                  }
                  const rows = document.querySelectorAll('.xterm-rows > div');
                  return Array.from(rows).map(r => r.textContent || '').join('\\n');
                }"""
            )
            lines.append(f"host_terminal_buffer={str(buf)[:240]!r}")
            buf_s = str(buf)
            host_markers = (
                "provide-uterm",
                "nested browser",
                "live stream",
                "Transcript",
                "Provide Shell Demo",
                "demo:",
                "demo starting",
            )
            if not buf_s or not any(m in buf_s for m in host_markers):
                raise RuntimeError(f"host terminal.html did not paint demo text: {buf!r}")
            lines.append("host_terminal_paint=ok")
            _c.close()
            _b.close()

        # VNC lease must be owned by test-admin (UTERM_TEST_MODE WS subject).
        st, vnc_lease = http_json(
            "POST",
            f"{base}/worker/{VNC_WORKER}/hijack/acquire",
            headers=headers,
            body={"owner": "vnc-recorder", "lease_s": 300},
        )
        if st != 200 or not isinstance(vnc_lease, dict) or not vnc_lease.get("hijack_id"):
            raise RuntimeError(f"vnc acquire failed status={st} body={vnc_lease!r}")
        hijack_id = str(vnc_lease["hijack_id"])
        lines.append(f"vnc_hijack={hijack_id}")
        page_url = f"{base}/_terminal/vnc.html?worker_id={VNC_WORKER}&hijack_id={hijack_id}&target_id={TARGET}"
        lines.append(f"vnc_page={page_url}")

        from playwright.sync_api import sync_playwright

        full_png = shots / "uterm-vnc-text-demos-full.png"
        desktop_png = shots / "uterm-vnc-text-demos-desktop.png"
        metrics_path = evidence / "video-metrics.json"
        storyboard = evidence / "storyboard"
        storyboard.mkdir(exist_ok=True)
        frame_paths: list[Path] = []
        metrics: dict[str, object] = {
            "demo_url": demo_url,
            "vnc_page": page_url,
        }

        def _open_vnc_page(browser: object) -> tuple[object, object]:
            """Open a clean VNC console page (one connect, no mid-stream reconnect)."""
            context = browser.new_context(  # type: ignore[attr-defined]
                viewport={"width": 1440, "height": 900},
                device_scale_factor=1,
            )
            context.add_cookies(
                [
                    {"name": "uterm_principal", "value": "test-admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_role", "value": "admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_tenant", "value": "lab", "domain": "127.0.0.1", "path": "/"},
                ]
            )
            page = context.new_page()
            page.set_extra_http_headers(
                {
                    "x-uterm-principal": "test-admin",
                    "x-uterm-role": "admin",
                    "x-uterm-tenant": "lab",
                }
            )
            page.goto(page_url, wait_until="domcontentloaded", timeout=45_000)
            page.wait_for_function(
                """() => {
                  const el = document.getElementById('vnc-status');
                  return el && el.dataset.state === 'connected';
                }""",
                timeout=30_000,
            )
            page.wait_for_function(
                """() => {
                  const c = document.querySelector('#vnc-screen canvas');
                  return c instanceof HTMLCanvasElement && c.width >= 640 && c.height >= 400;
                }""",
                timeout=20_000,
            )
            # Let the first full framebuffer settle (readable glyphs, no flash).
            page.wait_for_timeout(700)
            return context, page

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)

            # Progressive storyboard: fire a rapid chapter, then capture a *clean*
            # connected VNC frame. No mid-recording RFB disconnect (that flashed
            # Connecting… and shredded the demo). ffmpeg stitches frames into a
            # snappy website-style walkthrough.
            for chap_i, chapter in enumerate(LIVE_DEMO_CHAPTERS, start=1):
                for cmd in chapter:
                    st_send, body_send = send_shell_keys(base, headers, shell_hid, cmd)
                    if st_send >= 400:
                        lines.append(f"chap{chap_i}_err={st_send} {body_send!r}")
                    time.sleep(_KEY_GAP_S)
                # Nested browser paints via WS; nudge X so the lab desktop updates.
                time.sleep(0.35)
                nudge_lab_desktop(LAB)
                time.sleep(0.55)

                ctx, page = _open_vnc_page(browser)
                frame_path = storyboard / f"chap_{chap_i:02d}.png"
                page.screenshot(path=str(frame_path), full_page=True)
                frame_paths.append(frame_path)
                if chap_i == len(LIVE_DEMO_CHAPTERS):
                    page.screenshot(path=str(full_png), full_page=True)
                    page.locator("#vnc-screen").screenshot(path=str(desktop_png))
                    metrics.update(
                        page.evaluate(
                            """() => {
                              const status = document.getElementById('vnc-status');
                              const canvas = document.querySelector('#vnc-screen canvas');
                              const dims = document.getElementById('vnc-dims');
                              const screen = document.getElementById('vnc-screen');
                              const cs = screen ? getComputedStyle(screen) : null;
                              return {
                                status_state: status?.dataset?.state ?? null,
                                status_text: status?.textContent ?? null,
                                dims: dims?.textContent ?? null,
                                canvas_w: canvas?.width ?? 0,
                                canvas_h: canvas?.height ?? 0,
                                title: document.title,
                                screen_pad: cs?.padding ?? null,
                                screen_radius: cs?.borderRadius ?? null,
                              };
                            }"""
                        )
                    )
                lines.append(f"chapter_{chap_i}_frame={frame_path.name}")
                ctx.close()

            # Optional short continuous clip of the final state (stable RFB, no reconnect).
            tail_s = max(0.0, float(args.seconds))
            if tail_s > 0.2:
                video_dir = evidence / "video-raw"
                video_dir.mkdir(exist_ok=True)
                ctx = browser.new_context(
                    viewport={"width": 1440, "height": 900},
                    device_scale_factor=1,
                    record_video_dir=str(video_dir),
                    record_video_size={"width": 1440, "height": 900},
                )
                ctx.add_cookies(
                    [
                        {"name": "uterm_principal", "value": "test-admin", "domain": "127.0.0.1", "path": "/"},
                        {"name": "uterm_role", "value": "admin", "domain": "127.0.0.1", "path": "/"},
                        {"name": "uterm_tenant", "value": "lab", "domain": "127.0.0.1", "path": "/"},
                    ]
                )
                page = ctx.new_page()
                page.set_extra_http_headers(
                    {
                        "x-uterm-principal": "test-admin",
                        "x-uterm-role": "admin",
                        "x-uterm-tenant": "lab",
                    }
                )
                page.goto(page_url, wait_until="domcontentloaded", timeout=45_000)
                page.wait_for_function(
                    """() => document.getElementById('vnc-status')?.dataset?.state === 'connected'""",
                    timeout=30_000,
                )
                page.wait_for_timeout(int(tail_s * 1000))
                ctx.close()
                lines.append(f"tail_clip_s={tail_s}")

            browser.close()

        assert metrics.get("status_state") == "connected", metrics
        assert int(metrics.get("canvas_w") or 0) >= 640, metrics
        metrics_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")

        # Stitch storyboard frames into a snappy progressive webm (no connect flash).
        video_out = evidence / "uterm-vnc-text-demos.webm"
        if not frame_paths:
            raise RuntimeError("no storyboard frames produced")
        # ~1.1s per chapter — website-demo pace through the full script.
        list_file = storyboard / "frames.txt"
        list_file.write_text(
            "".join(f"file '{fp.resolve()}'\nduration 1.1\n" for fp in frame_paths)
            + f"file '{frame_paths[-1].resolve()}'\n",  # last frame needs a trailer entry
            encoding="utf-8",
        )
        ff = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-f",
                "concat",
                "-safe",
                "0",
                "-i",
                str(list_file),
                "-vsync",
                "vfr",
                "-pix_fmt",
                "yuv420p",
                "-c:v",
                "libvpx",
                "-b:v",
                "2M",
                "-auto-alt-ref",
                "0",
                str(video_out),
            ],
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
        if ff.returncode != 0 or not video_out.is_file():
            raise RuntimeError(f"ffmpeg storyboard failed: {(ff.stderr or ff.stdout)[:800]}")
        lines.append(f"video={video_out}")
        lines.append(f"storyboard_frames={len(frame_paths)}")
        lines.append(f"full_png={full_png}")
        lines.append(f"desktop_png={desktop_png}")

        # Publish into demo/vnc-lab (png committed; webm may be gitignored).
        demo = root / "demo" / "vnc-lab"
        demo_shots = demo / "screenshots"
        demo_shots.mkdir(parents=True, exist_ok=True)
        for src, name in (
            (full_png, "uterm-vnc-text-demos-full.png"),
            (desktop_png, "uterm-vnc-text-demos-desktop.png"),
            (full_png, "uterm-vnc-console.png"),
        ):
            (demo_shots / name).write_bytes(src.read_bytes())
        (demo / "uterm-vnc-text-demos.webm").write_bytes(video_out.read_bytes())
        (demo / "video-metrics.json").write_text(metrics_path.read_text(encoding="utf-8"), encoding="utf-8")
        lines.append("published=demo/vnc-lab/")

        summary = "\n".join(lines) + "\nvideo_proof=ok\n"
        (evidence / "video-summary.log").write_text(summary, encoding="utf-8")
        print(summary)
        print(json.dumps(metrics, indent=2))
        return 0
    except Exception as exc:
        err = "\n".join(lines) + f"\nerror={exc}\n"
        (evidence / "video-error.log").write_text(err, encoding="utf-8")
        print(err, file=sys.stderr)
        return 1
    finally:
        prove.stop_server(proc)
        vnc_lab._remove_container(LAB)


if __name__ == "__main__":
    raise SystemExit(main())
