#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Record the recursive "nautilus" tiling panels page with distinct scenes.

Each of the three lab RFB targets runs a *different* ushell session that has
rendered a different full-screen scene (a rainbow gradient, a cat, a matrix
rain) via the ``render`` command. The nautilus panes fan out across the three
targets, so the tiling clearly shows multiple *distinct* VNC browsers in play —
not the same terminal repeated. Panes shrink (font and all) as the spiral winds
inward via noVNC's scale-viewport.

Usage (repo root)::

    uv run python scripts/record_uterm_vnc_panels_demo.py --skip-build
"""

from __future__ import annotations

import argparse
import colorsys
import json
import os
import subprocess
import sys
import time
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import prove_vnc_lab as vnc_lab  # noqa: E402
import record_uterm_vnc_demo_video as base  # noqa: E402
import record_uterm_vnc_nested_demo as nested  # noqa: E402

# (session_id, display label, scene image filename). One per lab target so each
# VNC pane shows a visibly different scene.
SCENES = [
    ("scene-rainbow", "Rainbow", "rainbow.png"),
    ("scene-cat", "Cat", "cat.png"),
    ("scene-matrix", "Matrix", "matrix.png"),
]


def _generate_scenes(out_dir: Path) -> None:
    """Write three distinct scene images the ushell `render` command turns to ANSI."""
    from PIL import Image

    out_dir.mkdir(parents=True, exist_ok=True)
    w, h = 320, 180
    # Rainbow: smooth horizontal hue sweep.
    rainbow = Image.new("RGB", (w, h))
    rp = rainbow.load()
    for x in range(w):
        r, g, b = colorsys.hsv_to_rgb(x / w, 1.0, 1.0)
        col = (int(r * 255), int(g * 255), int(b * 255))
        for y in range(h):
            rp[x, y] = col
    rainbow.save(out_dir / "rainbow.png")
    # Cat: a simple colour cat face on a dark ground.
    cat = Image.new("RGB", (w, h), (18, 18, 28))
    cp = cat.load()
    cx, cy = w // 2, h // 2 + 8
    for x in range(w):
        for y in range(h):
            if (x - cx) ** 2 + ((y - cy) * 1.2) ** 2 < 60**2:
                cp[x, y] = (95, 72, 52)
    for x in range(cx - 55, cx - 15):
        for y in range(cy - 70, cy - 30):
            if (x - (cx - 55)) < (y - (cy - 70)) < (x - (cx - 55)) + 18:
                cp[x, y] = (95, 72, 52)
    for x in range(cx + 15, cx + 55):
        for y in range(cy - 70, cy - 30):
            if ((cx + 55) - x) < (y - (cy - 70)) < ((cx + 55) - x) + 18:
                cp[x, y] = (95, 72, 52)
    for ex in (cx - 22, cx + 22):
        for x in range(ex - 8, ex + 8):
            for y in range(cy - 15, cy + 5):
                if (x - ex) ** 2 + (y - (cy - 5)) ** 2 < 8**2:
                    cp[x, y] = (70, 225, 95)
    cat.save(out_dir / "cat.png")
    # Matrix: green rain columns.
    matrix = Image.new("RGB", (w, h), (0, 0, 0))
    mp = matrix.load()
    for x in range(0, w, 6):
        hlen = (x * 7) % h
        for y in range(hlen):
            mp[x, y] = (0, max(0, 255 - (hlen - y) * 4), 0)
    matrix.save(out_dir / "matrix.png")


def _write_panels_config(path: Path, *, host: str, port: int) -> None:
    """Server config: three ushell scene sessions + N VNC-lease workers + N targets."""
    blocks: list[str] = []
    for sid, label, _fname in SCENES:
        blocks.append(
            f"""
[[sessions]]
session_id = "{sid}"
display_name = "{label}"
connector_type = "ushell"
input_mode = "hijack"
auto_start = true
tags = ["scene"]
"""
        )
    for wk in nested.NEST_LEASE_WORKERS:
        blocks.append(
            f"""
[[sessions]]
session_id = "{wk}"
display_name = "VNC lease {wk}"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["vnc-lab"]
"""
        )
    for tgt, p in zip(nested.NEST_TARGETS, nested.NEST_PORTS, strict=True):
        blocks.append(
            f"""
[[graphical_targets]]
target_id = "{tgt}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{p}"
name = "Nested RFB {tgt}"
enabled = true
width = 1280
height = 936
"""
        )
    body = f"""\
# Auto-generated by record_uterm_vnc_panels_demo.py — do not commit.
[server]
host = "{host}"
port = {port}
public_base_url = "http://127.0.0.1:{port}"
title = "uterm nautilus panels demo"

[auth]
mode = "header"
header_mode_acknowledged = true
principal_header = "x-uterm-principal"
role_header = "x-uterm-role"
worker_bearer_token = "{base.LAB_WORKER_TOKEN}"
trusted_proxy_ips = [
  "127.0.0.1", "::1",
  "192.168.5.1", "192.168.5.2", "192.168.65.1", "192.168.65.2",
  "172.17.0.1", "172.18.0.1", "10.0.0.1",
]

[ui]
app_path = "/app"
assets_path = "/_terminal"

[recording]
enabled_by_default = false

[security]
block_private_connector_targets = false
{"".join(blocks)}"""
    path.write_text(body, encoding="utf-8")


def _drive_render(base_url: str, headers: dict[str, str], session: str, scene_path: Path) -> None:
    """Render *scene_path* into the ushell scene session as full-screen ANSI.

    ushell reports ``input_mode=open`` on hello, so switch it to hijack first,
    then acquire a lease and feed the ``render`` command.
    """
    base.http_json("POST", f"{base_url}/worker/{session}/input_mode", headers=headers, body={"input_mode": "hijack"})
    hid = nested._acquire_lease(base_url, headers, session)
    # ushell render --loop: file:// path on the server host → truecolor ANSI
    # frames. Looping keeps the scene on screen (no trailing prompt), so a fresh
    # browser/RFB viewer's cached snapshot stays the rendered scene.
    base.send_shell_keys(
        base_url,
        headers,
        hid,
        f"render --loop --cols 96 --rows 30 file://{scene_path.resolve()}\r",
        session=session,
    )
    # Force the worker to re-snapshot so the hub caches the rendered scene as the
    # session's last_snapshot. Without this a browser/RFB viewer connecting later
    # gets the stale connect-time prompt snapshot, not the scene (render emits
    # `term` frames, which don't refresh last_snapshot).
    time.sleep(0.4)
    base.http_json("GET", f"{base_url}/worker/{session}/hijack/{hid}/snapshot", headers=headers)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", default=None)
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--splits", type=int, default=5, help="how many times to spiral-split (nautilus)")
    args = parser.parse_args(argv)

    evidence = base._evidence_dir(args.evidence_dir)
    root = base._repo_root()
    shots = evidence / "screenshots"
    shots.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [f"evidence={evidence}"]

    if not vnc_lab._docker_available():
        (evidence / "docker-unavailable.log").write_text("docker missing\n", encoding="utf-8")
        return 2
    if not args.skip_build:
        vnc_lab.build_image(root=root, log_path=evidence / "lab-build.log")

    scenes_dir = evidence / "scenes"
    _generate_scenes(scenes_dir)

    server_port = base._free_port()
    cfg = evidence / "panels-server.toml"
    _write_panels_config(cfg, host="0.0.0.0", port=server_port)

    env = {**os.environ, "UTERM_TEST_MODE": "1", "UTERM_API_ONLY": "0"}
    log_f = (evidence / "panels-server.log").open("w", encoding="utf-8")
    cmd = [str(root / ".venv" / "bin" / "uterm"), "server", "--config", str(cfg)]
    if not Path(cmd[0]).is_file():
        cmd = [sys.executable, "-m", "provide.uterm.cli", "server", "--config", str(cfg)]
    proc = subprocess.Popen(cmd, cwd=str(root), stdout=log_f, stderr=subprocess.STDOUT, text=True, env=env)

    headers = {
        "x-uterm-principal": "test-admin",
        "x-uterm-role": "admin",
        "x-uterm-tenant": "lab",
        "Content-Type": "application/json",
    }
    base_url = f"http://127.0.0.1:{server_port}"
    metrics: dict[str, object] = {}
    lab_names = nested.NEST_NAMES
    try:
        base.prove.wait_http(f"{base_url}/readyz", timeout=60.0)
        lines.append(f"server_ready={base_url}")

        # Wait for every scene session to connect, then render its scene.
        for sid, _label, fname in SCENES:
            connected = False
            for _ in range(80):
                st, body = base.http_json("GET", f"{base_url}/api/sessions/{sid}", headers=headers)
                if st == 200 and isinstance(body, dict) and body.get("connected"):
                    connected = True
                    break
                time.sleep(0.15)
            if not connected:
                raise RuntimeError(f"scene session {sid} never connected")
            _drive_render(base_url, headers, sid, scenes_dir / fname)
        time.sleep(1.5)
        lines.append("scenes_rendered=ok")

        # Each lab views a *different* scene session so the panes are distinct.
        hids = [nested._acquire_lease(base_url, headers, w) for w in nested.NEST_LEASE_WORKERS]
        for (name, port), (sid, _label, _fname) in zip(
            zip(lab_names, nested.NEST_PORTS, strict=True), SCENES, strict=True
        ):
            demo_url = (
                f"http://{base._HOST_FROM_DOCKER}:{server_port}/_terminal/terminal.html?worker_id={sid}&role=browser"
            )
            nested._start_nested_lab(name=name, demo_url=demo_url, host_plain=port)
            if not nested._wait_lab_rfb(name):
                raise RuntimeError(f"lab {name} RFB never ready")
        time.sleep(3.0)

        # Panels VNC pool = the three distinct-scene targets (fan-out).
        vnc_pool = ",".join(
            f"{w}~{h}~{t}" for w, h, t in zip(nested.NEST_LEASE_WORKERS, hids, nested.NEST_TARGETS, strict=True)
        )
        panels_url = f"{base_url}/_terminal/panels.html?vnc={vnc_pool}"
        lines.append(f"panels_url={panels_url}")

        from playwright.sync_api import sync_playwright

        raw_dir = evidence / "panels-video-raw"
        raw_dir.mkdir(exist_ok=True)
        full_png = shots / "uterm-vnc-fractal-full.png"
        live_webm: Path | None = None
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                viewport={"width": 1600, "height": 960},
                device_scale_factor=1,
                record_video_dir=str(raw_dir),
                record_video_size={"width": 1600, "height": 960},
            )
            context.add_cookies(
                [
                    {"name": "uterm_principal", "value": "test-admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_role", "value": "admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_tenant", "value": "lab", "domain": "127.0.0.1", "path": "/"},
                ]
            )
            page = context.new_page()
            page.set_extra_http_headers(
                {"x-uterm-principal": "test-admin", "x-uterm-role": "admin", "x-uterm-tenant": "lab"}
            )
            page.goto(panels_url, wait_until="domcontentloaded", timeout=45_000)
            page.wait_for_function("() => (window.utermPanels?.leafCount ?? 0) >= 2", timeout=30_000)
            page.wait_for_function(
                "() => document.querySelector('.pane-vnc[data-state=\"connected\"]') !== null",
                timeout=40_000,
            )
            page.wait_for_timeout(2500)
            for _ in range(max(0, int(args.splits))):
                page.click("#panels-nautilus")
                page.wait_for_timeout(3000)
            page.wait_for_timeout(4000)
            page.screenshot(path=str(full_png), full_page=True)
            metrics.update(
                page.evaluate(
                    "() => ({ panes: window.utermPanels?.leafCount ?? 0,"
                    " connectedVnc: document.querySelectorAll('.pane-vnc[data-state=\"connected\"]').length }) "
                )
            )
            video = page.video
            context.close()
            browser.close()
            if video is not None:
                try:
                    live_webm = Path(video.path())
                except Exception:  # pragma: no cover - best-effort
                    live_webm = None

        lines.append(f"metrics={json.dumps(metrics)}")
        if int(metrics.get("panes", 0) or 0) < 2:
            raise RuntimeError(f"panels never rendered: {metrics}")

        video_out = evidence / "uterm-vnc-fractal.mp4"
        if live_webm and live_webm.is_file():
            nested._encode_mp4(live_webm, video_out)
            base._assert_video_not_black(video_out)
            lines.append(f"video={video_out}")

        demo = root / "demo" / "vnc-lab"
        (demo / "screenshots").mkdir(parents=True, exist_ok=True)
        (demo / "screenshots" / "uterm-vnc-fractal-full.png").write_bytes(full_png.read_bytes())
        if video_out.is_file():
            (demo / "uterm-vnc-fractal.mp4").write_bytes(video_out.read_bytes())
        (evidence / "panels-summary.log").write_text("\n".join(lines) + "\npanels_proof=ok\n", encoding="utf-8")
        print("\n".join(lines))
        return 0
    except Exception as exc:
        lines.append(f"error={exc}")
        (evidence / "panels-summary.log").write_text("\n".join(lines) + "\npanels_proof=FAIL\n", encoding="utf-8")
        print("\n".join(lines), file=sys.stderr)
        return 1
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        for name in lab_names:
            vnc_lab._remove_container(name)


if __name__ == "__main__":
    raise SystemExit(main())
