#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Record video: first-party uterm VNC console showing lab browser on text demos.

End-to-end proof (not mocked)::

  1. Start uterm server (shell demo session + RFB graphical targets)
  2. Start uterm-test-vnc lab with Chromium pointed at the host's
     ``/_terminal/terminal.html`` text console (and a second tab/window path)
  3. Drive live shell output (text-based demos) into the session
  4. Open host Playwright on first-party ``vnc.html`` and record webm + stills

Usage (repo root)::

    uv run python scripts/record_uterm_vnc_demo_video.py
    uv run python scripts/record_uterm_vnc_demo_video.py --seconds 18 --skip-build
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import prove_uterm_vnc_console as prove  # noqa: E402
import prove_vnc_lab as vnc_lab  # noqa: E402

LAB = "uterm-vnc-demo-video"
SHELL_SESSION = "provide-shell"
VNC_WORKER = prove.SERVER_SESSION
TARGET = prove.TARGET_PLAIN
LAB_WORKER_TOKEN = "vnc-lab-worker-bearer-token-32chars"  # noqa: S105 — lab fixture

# Host gateway seen from Docker Desktop / Colima / Linux docker0.
_HOST_FROM_DOCKER = "host.docker.internal"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _evidence_dir(explicit: str | None) -> Path:
    for key in (explicit, os.environ.get("EVIDENCE_DIR"), os.environ.get("SCRATCH")):
        if key:
            p = Path(key)
            p.mkdir(parents=True, exist_ok=True)
            return p
    p = _repo_root() / "demo" / "vnc-lab"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("0.0.0.0", 0))
        return int(s.getsockname()[1])


def write_demo_server_config(
    path: Path,
    *,
    host: str,
    port: int,
    plain_port: int,
    tls_port: int,
) -> None:
    """Server config: text shell demo + VNC lab targets; bind all interfaces."""
    body = f"""\
# Auto-generated by record_uterm_vnc_demo_video.py — do not commit.
[server]
host = "{host}"
port = {port}
public_base_url = "http://127.0.0.1:{port}"
title = "uterm VNC + text demos"

[auth]
mode = "header"
header_mode_acknowledged = true
principal_header = "x-uterm-principal"
role_header = "x-uterm-role"
worker_bearer_token = "{LAB_WORKER_TOKEN}"
# Non-loopback bind requires an allowlist; local recorder + Docker Desktop peers.
trusted_proxy_ips = [
  "127.0.0.1",
  "::1",
  "192.168.5.1",
  "192.168.5.2",
  "192.168.65.1",
  "192.168.65.2",
  "172.17.0.1",
  "172.18.0.1",
  "10.0.0.1",
]

[ui]
app_path = "/app"
assets_path = "/_terminal"

[recording]
enabled_by_default = false
directory = "{path.parent / "recordings"}"

[security]
block_private_connector_targets = false

# Text-based shell demo the lab Chromium will open.
# hijack mode so the recorder can inject live demo keystrokes via REST.
[[sessions]]
session_id = "{SHELL_SESSION}"
display_name = "Provide Shell Demo"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["demo", "text"]

# Second shell so the demo can flip between sessions.
[[sessions]]
session_id = "demo-shell-2"
display_name = "Demo Shell Two"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["demo", "text"]
# Worker used only for VNC hijack lease (authz gate for /gui/vnc).
[[sessions]]
session_id = "{VNC_WORKER}"
display_name = "VNC lease shell"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["vnc-lab"]

[[graphical_targets]]
target_id = "{TARGET}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{plain_port}"
name = "VNC Lab Plain"
enabled = true
width = 1280
height = 720

[[graphical_targets]]
target_id = "{prove.TARGET_TLS}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{tls_port}"
name = "VNC Lab TLS"
enabled = true

[graphical_targets.config]
tls = true
tls_insecure = true
"""
    path.write_text(body, encoding="utf-8")


def start_lab_with_demo_url(*, name: str, demo_url: str) -> tuple[int, int]:
    """Start lab container; Chromium opens *demo_url* (host uterm text console)."""
    vnc_lab._remove_container(name)
    result = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            name,
            "--shm-size",
            vnc_lab.DEFAULT_SHM,
            "--add-host=host.docker.internal:host-gateway",
            "-p",
            f"0:{vnc_lab.RFB_PLAIN_PORT}",
            "-p",
            f"0:{vnc_lab.RFB_SSL_PORT}",
            "-e",
            f"DEMO_URL={demo_url}",
            vnc_lab.IMAGE_NAME,
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"docker run failed: {result.stderr.strip()[:500]}")
    return vnc_lab._mapped_port(name, vnc_lab.RFB_PLAIN_PORT), vnc_lab._mapped_port(name, vnc_lab.RFB_SSL_PORT)


def http_json(method: str, url: str, *, headers: dict[str, str], body: dict | None = None) -> tuple[int, object]:
    data = None if body is None else json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers, method=method)  # noqa: S310
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310
            raw = resp.read().decode("utf-8")
            return resp.status, json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        try:
            parsed: object = json.loads(raw) if raw else {}
        except json.JSONDecodeError:
            parsed = raw
        return exc.code, parsed


def drive_text_demos(base: str, headers: dict[str, str], *, session: str = SHELL_SESSION) -> list[str]:
    """Inject live text demo activity into a shell session via REST hijack/send."""
    log: list[str] = []
    status, payload = http_json(
        "POST",
        f"{base}/worker/{session}/hijack/acquire",
        headers=headers,
        body={"owner": "demo-driver", "lease_s": 180},
    )
    if status != 200 or not isinstance(payload, dict):
        log.append(f"acquire_{session}=status_{status} body={payload!r}")
        return log
    hid = str(payload["hijack_id"])
    log.append(f"acquire_{session}={hid}")
    commands = [
        "clear\r",
        "echo '════════════════════════════════════════'\r",
        "echo '  provide-uterm · text-based shell demo'\r",
        "echo '════════════════════════════════════════'\r",
        "echo\r",
        "printf '\\033[1;36m[demo]\\033[0m whoami → ' && whoami\r",
        "printf '\\033[1;32m[demo]\\033[0m pwd    → ' && pwd\r",
        "echo\r",
        "echo -e '\\033[38;5;196mR\\033[38;5;202mA\\033[38;5;208mI\\033[38;5;214mN\\033[38;5;220mB\\033[38;5;226mO\\033[38;5;190mW\\033[0m shell output'\r",
        "echo\r",
        "ls -la | head -12\r",
        "echo\r",
        "echo -e '\\033[1;35m[demo]\\033[0m date → ' && date\r",
        "echo -e '\\033[1;33m[demo]\\033[0m uname → ' && uname -a | cut -c1-72\r",
        "echo\r",
        "for i in 1 2 3 4 5 6 7 8; do printf '\\033[38;5;%sm█\\033[0m' $((160+i*4)); done; echo\r",
        "echo\r",
        "echo '── live session stream ─────────────────'\r",
    ]
    for cmd in commands:
        st, body = http_json(
            "POST",
            f"{base}/worker/{session}/hijack/{hid}/send",
            headers=headers,
            body={"keys": cmd, "timeout_ms": 1500},
        )
        if st >= 400:
            log.append(f"send_err={st} {body!r}")
        time.sleep(0.15)
    log.append(f"drove_{session}=ok")
    return log


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", default=None)
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--seconds", type=float, default=16.0, help="recording length after connect")
    args = parser.parse_args(argv)

    evidence = _evidence_dir(args.evidence_dir)
    root = _repo_root()
    shots = evidence / "screenshots"
    shots.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [f"evidence={evidence}"]

    if not vnc_lab._docker_available():
        (evidence / "docker-unavailable.log").write_text("docker missing\n", encoding="utf-8")
        return 2

    if not args.skip_build:
        vnc_lab.build_image(root=root, log_path=evidence / "lab-build.log")

    # --- uterm server (reachable from Docker via host.docker.internal) ---
    host_bind = "0.0.0.0"
    port = _free_port()
    # Lab RFB ports unknown until container starts — write config in two phases:
    # start lab first with placeholder, then rewrite? Better: start lab after
    # we know we need host port for DEMO_URL; RFB host ports from lab after start.
    # Order: start lab with example.com first, then server, then restart chromium?
    # Cleaner: start lab after server, DEMO_URL points at host terminal.

    # Start a temporary lab only after server is up. Server needs RFB ports for
    # graphical_targets — so start lab first, then server, DEMO_URL already set.
    # Chicken/egg: DEMO_URL needs server port; graphical_targets need lab ports.
    # Resolution: start lab with DEMO_URL; start server with mapped RFB ports.

    # Phase 1: free ports reserved? Start server on fixed free port first without
    # graphical targets... but we need them for VNC. Start lab first:
    plain_probe = _free_port()  # unused; real mapping comes from docker
    del plain_probe

    # Start lab with DEMO_URL to host terminal (server not up yet — chromium retries).
    # Actually chromium launches once at entrypoint. So server must be up first.
    # Start server with loopback RFB that isn't ready yet → VNC dial fails until lab up.
    # Sequence:
    #  1. Start empty placeholder? No.
    #  2. Start lab with DEMO_URL=about:blank, then server, then docker exec chromium.
    #  3. Or: start lab, get RFB ports, start server, docker exec kill chromium + relaunch.

    # Use approach 3 via entrypoint re-run of browser:
    # docker exec env DEMO_URL=... bash -c 'pkill chromium; chromium ...'

    # Simpler approach used here:
    #  1. Start lab with DEMO_URL pointing at host (server will be ready within ~2s of chrome start)
    #  2. Start server immediately after docker run returns (before chrome finishes booting X)
    # Xvfb+fluxbox takes several seconds before chromium — enough to start server.

    # Pre-choose server port. Lab boots with a stable public page first so the
    # container does not exit when host demos are not yet listening (entrypoint
    # fails if Chromium exits early). We navigate to the text demo after.
    server_port = port
    demo_url = (
        f"http://{_HOST_FROM_DOCKER}:{server_port}/_terminal/terminal.html?worker_id={SHELL_SESSION}&role=browser"
    )
    lines.append(f"demo_url={demo_url}")

    # Stable boot URL (always reachable) — switch to demo_url after server is up.
    plain_port, tls_port = start_lab_with_demo_url(name=LAB, demo_url="https://example.com")
    lines.append(f"lab_plain={plain_port} lab_tls={tls_port}")
    cfg = evidence / "server.toml"
    write_demo_server_config(
        cfg,
        host=host_bind,
        port=server_port,
        plain_port=plain_port,
        tls_port=tls_port,
    )

    # TEST_MODE so lab browser WS auth succeeds without cookies.
    env = {**os.environ, "UTERM_TEST_MODE": "1", "UTERM_API_ONLY": "0"}
    # Patch start_server to pass env — call uvicorn path via prove with env.
    log_path = evidence / "server.log"
    cmd = [
        str(root / ".venv" / "bin" / "uterm"),
        "server",
        "--config",
        str(cfg),
    ]
    if not Path(cmd[0]).is_file():
        cmd = [sys.executable, "-m", "provide.uterm.cli", "server", "--config", str(cfg)]
    log_f = log_path.open("w", encoding="utf-8")
    log_f.write(f"$ {' '.join(cmd)}\nUTERM_TEST_MODE=1\n")
    log_f.flush()
    proc = subprocess.Popen(
        cmd,
        cwd=str(root),
        stdout=log_f,
        stderr=subprocess.STDOUT,
        text=True,
        env=env,
    )
    proc._log_f = log_f  # type: ignore[attr-defined]

    # UTERM_TEST_MODE mints WS principal subject_id="test-admin". REST acquires
    # must use the same subject so /gui/vnc lease ownership checks pass.
    headers = {
        "x-uterm-principal": "test-admin",
        "x-uterm-role": "admin",
        "x-uterm-tenant": "lab",
        "Content-Type": "application/json",
    }
    base = f"http://127.0.0.1:{server_port}"
    try:
        prove.wait_http(f"{base}/readyz", timeout=60.0)
        lines.append(f"server_ready={base}")
        vnc_lab.wait_rfb("127.0.0.1", plain_port, retries=80, delay=0.5)
        lines.append("lab_rfb=ok")

        # Navigate lab Chromium to host text demos.
        # Never match free-text patterns that include this shell's argv (self-kill).
        # `killall chromium` matches the process name only.
        nav_script = (
            "set +e; "
            "killall chromium 2>/dev/null; "
            "killall chrome 2>/dev/null; "
            "sleep 1; "
            "BIN=/usr/lib/chromium/chromium; "
            "echo bin=$BIN; "
            "export DISPLAY=:99; "
            f"nohup $BIN --no-sandbox --disable-gpu --disable-dev-shm-usage "
            f"--no-first-run --window-size=1280,720 --window-position=0,0 "
            f"{demo_url!r} >>/var/log/vnc-lab/chrome-relaunch.log 2>&1 & "
            "echo relaunched_pid=$!; "
            "sleep 2; "
            "ps -C chromium -o pid,args= 2>/dev/null | head -5; "
            "echo done"
        )
        relaunch = subprocess.run(
            ["docker", "exec", LAB, "bash", "-lc", nav_script],
            capture_output=True,
            text=True,
            timeout=45,
            check=False,
        )
        lines.append(
            f"chrome_relaunch_rc={relaunch.returncode} "
            f"out={relaunch.stdout.strip()[:400]!r} "
            f"err={relaunch.stderr.strip()[:200]!r}"
        )
        vnc_lab.wait_rfb("127.0.0.1", plain_port, retries=30, delay=0.3)
        time.sleep(4.0)

        # Drive text demos into the shell the lab browser is watching.
        drive_log = drive_text_demos(base, headers, session=SHELL_SESSION)
        lines.extend(drive_log)
        shell_hid_held: str | None = None
        for entry in drive_log:
            if entry.startswith("acquire_provide-shell="):
                shell_hid_held = entry.split("=", 1)[1]
                if len(shell_hid_held) == 8:
                    # only prefix logged — re-acquire not needed if we store full id
                    shell_hid_held = None
        # Keep full hijack id by re-reading last successful acquire inside drive —
        # re-drive is skipped; store full id from a dedicated acquire after chrome up.
        st, shell_payload = http_json(
            "POST",
            f"{base}/worker/{SHELL_SESSION}/hijack/acquire",
            headers=headers,
            body={"owner": "demo-driver", "lease_s": 300},
        )
        if st == 200 and isinstance(shell_payload, dict):
            shell_hid_held = str(shell_payload["hijack_id"])
            # Extra banner now that browser is up
            for cmd in (
                "echo\r",
                "echo '>>> browser is watching this shell via uterm VNC <<<'\r",
                "echo\r",
            ):
                http_json(
                    "POST",
                    f"{base}/worker/{SHELL_SESSION}/hijack/{shell_hid_held}/send",
                    headers=headers,
                    body={"keys": cmd, "timeout_ms": 1200},
                )
        lines.append(f"shell_hid_held={shell_hid_held}")
        shell_hid = shell_hid_held
        lines.append(f"shell_lease={shell_hid}")

        # VNC lease must be owned by test-admin (UTERM_TEST_MODE WS subject).
        st, vnc_lease = http_json(
            "POST",
            f"{base}/worker/{VNC_WORKER}/hijack/acquire",
            headers=headers,
            body={"owner": "vnc-recorder", "lease_s": 300},
        )
        if st != 200 or not isinstance(vnc_lease, dict) or not vnc_lease.get("hijack_id"):
            raise RuntimeError(f"vnc acquire failed status={st} body={vnc_lease!r}")
        hijack_id = str(vnc_lease["hijack_id"])
        lines.append(f"vnc_hijack={hijack_id}")
        page_url = f"{base}/_terminal/vnc.html?worker_id={VNC_WORKER}&hijack_id={hijack_id}&target_id={TARGET}"
        lines.append(f"vnc_page={page_url}")

        from playwright.sync_api import sync_playwright

        video_dir = evidence / "video-raw"
        video_dir.mkdir(exist_ok=True)
        full_png = shots / "uterm-vnc-text-demos-full.png"
        desktop_png = shots / "uterm-vnc-text-demos-desktop.png"
        metrics_path = evidence / "video-metrics.json"

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                viewport={"width": 1440, "height": 900},
                device_scale_factor=2,
                record_video_dir=str(video_dir),
                record_video_size={"width": 1440, "height": 900},
                extra_http_headers={
                    "x-uterm-principal": "test-admin",
                    "x-uterm-role": "admin",
                    "x-uterm-tenant": "lab",
                },
            )
            context.add_cookies(
                [
                    {"name": "uterm_principal", "value": "test-admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_role", "value": "admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_tenant", "value": "lab", "domain": "127.0.0.1", "path": "/"},
                ]
            )
            page = context.new_page()
            page.goto(page_url, wait_until="domcontentloaded", timeout=45_000)
            page.wait_for_function(
                """() => {
                  const el = document.getElementById('vnc-status');
                  return el && el.dataset.state === 'connected';
                }""",
                timeout=30_000,
            )
            # Wait for remote Chromium + terminal paint.
            page.wait_for_timeout(3500)

            stop_at = time.time() + max(10.0, float(args.seconds))
            tick = 0
            while time.time() < stop_at:
                tick += 1
                if shell_hid:
                    http_json(
                        "POST",
                        f"{base}/worker/{SHELL_SESSION}/hijack/{shell_hid}/send",
                        headers=headers,
                        body={
                            "keys": (
                                f"echo -e '\\033[1;36m[tick {tick}]\\033[0m "
                                f"$(date +%H:%M:%S) · provide-uterm text demo'\r"
                            ),
                            "timeout_ms": 1200,
                        },
                    )
                page.wait_for_timeout(1800)
                if tick in (2, 5, 8):
                    page.screenshot(path=str(full_png), full_page=True)

            metrics = page.evaluate(
                """() => {
                  const status = document.getElementById('vnc-status');
                  const canvas = document.querySelector('#vnc-screen canvas');
                  const dims = document.getElementById('vnc-dims');
                  return {
                    status_state: status?.dataset?.state ?? null,
                    status_text: status?.textContent ?? null,
                    dims: dims?.textContent ?? null,
                    canvas_w: canvas?.width ?? 0,
                    canvas_h: canvas?.height ?? 0,
                    title: document.title,
                  };
                }"""
            )
            metrics["demo_url"] = demo_url
            metrics["vnc_page"] = page_url
            metrics_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
            assert metrics["status_state"] == "connected", metrics
            assert metrics["canvas_w"] >= 640, metrics

            page.screenshot(path=str(full_png), full_page=True)
            page.locator("#vnc-screen").screenshot(path=str(desktop_png))
            context.close()
            browser.close()
        webms = sorted(video_dir.glob("*.webm"), key=lambda p: p.stat().st_mtime)
        video_out = evidence / "uterm-vnc-text-demos.webm"
        if not webms:
            raise RuntimeError("no playwright webm produced")
        webms[-1].replace(video_out)
        lines.append(f"video={video_out}")
        lines.append(f"full_png={full_png}")
        lines.append(f"desktop_png={desktop_png}")

        # Publish into demo/vnc-lab (png committed; webm may be gitignored).
        demo = root / "demo" / "vnc-lab"
        demo_shots = demo / "screenshots"
        demo_shots.mkdir(parents=True, exist_ok=True)
        for src, name in (
            (full_png, "uterm-vnc-text-demos-full.png"),
            (desktop_png, "uterm-vnc-text-demos-desktop.png"),
            (full_png, "uterm-vnc-console.png"),
        ):
            (demo_shots / name).write_bytes(src.read_bytes())
        (demo / "uterm-vnc-text-demos.webm").write_bytes(video_out.read_bytes())
        (demo / "video-metrics.json").write_text(metrics_path.read_text(encoding="utf-8"), encoding="utf-8")
        lines.append("published=demo/vnc-lab/")

        summary = "\n".join(lines) + "\nvideo_proof=ok\n"
        (evidence / "video-summary.log").write_text(summary, encoding="utf-8")
        print(summary)
        print(json.dumps(metrics, indent=2))
        return 0
    except Exception as exc:
        err = "\n".join(lines) + f"\nerror={exc}\n"
        (evidence / "video-error.log").write_text(err, encoding="utf-8")
        print(err, file=sys.stderr)
        return 1
    finally:
        prove.stop_server(proc)
        vnc_lab._remove_container(LAB)


if __name__ == "__main__":
    raise SystemExit(main())
