#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: AGPL-3.0-or-later
#
"""Record the "turtles all the way down" nested VNC demo.

Three levels of nested browsers, each viewing the next through the uterm VNC
console, ending in a live text terminal::

  host vnc.html  ->  lab2 (browser)
                       -> vnc.html -> lab1 (browser)
                                        -> vnc.html -> lab0 (browser)
                                                         -> terminal.html (shell)

Each inner lab's Chromium loads the first-party ``vnc.html`` pointed at the next
lab's RFB target; the server relays RFB through its human-VNC path. Auth works
because ``UTERM_TEST_MODE=1`` mints the ``test-admin`` WS principal, and the
recorder pre-acquires a 300s hijack lease per level (baked into each DEMO_URL).

Usage (repo root)::

    uv run python scripts/record_uterm_vnc_nested_demo.py --skip-build
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import prove_vnc_lab as vnc_lab  # noqa: E402
import record_uterm_vnc_demo_video as base  # noqa: E402

# Innermost -> outermost. lab0 shows the terminal; lab1 shows lab0; lab2 shows lab1.
LEVELS = 3
NEST_NAMES = [f"uterm-nest-{i}" for i in range(LEVELS)]
NEST_PORTS = [25900 + 2 * i for i in range(LEVELS)]  # host-published plain RFB ports
NEST_TARGETS = [f"nest-tgt-{i}" for i in range(LEVELS)]
NEST_LEASE_WORKERS = [f"nest-vnc-{i}" for i in range(LEVELS)]
SHELL_SESSION = base.SHELL_SESSION
LAB_GEOMETRY = base.LAB_GEOMETRY

# Innermost terminal content (seeded before recording so every pane reads).
# ANSI escapes ride through /say verbatim (the shell connector doesn't strip
# them), so the transcript renders in colour — a rainbow bar + a little cat.
_ESC = "\x1b"
SEED_LINES = [
    "/clear\r",
    "/nick demo\r",
    f"/say {_ESC}[1;35m✦ provide-uterm · colour demo ✦{_ESC}[0m\r",
    f"/say {_ESC}[41m  {_ESC}[42m  {_ESC}[43m  {_ESC}[44m  {_ESC}[45m  {_ESC}[46m  {_ESC}[0m  rainbow\r",
    f"/say {_ESC}[33m /\\_/\\ {_ESC}[0m  nautilus cat\r",
    f"/say {_ESC}[33m( {_ESC}[92mo{_ESC}[33m.{_ESC}[92mo{_ESC}[33m ){_ESC}[0m  purring in every pane\r",
    f"/say {_ESC}[33m > {_ESC}[91m^{_ESC}[33m < {_ESC}[0m  meow\r",
    f"/say {_ESC}[36m[1]{_ESC}[0m host VNC  {_ESC}[36m[2]{_ESC}[0m nested  {_ESC}[36m[3]{_ESC}[0m fractal\r",
    f"/say {_ESC}[32mready · colour demo complete{_ESC}[0m\r",
]


def _write_nested_config(path: Path, *, host: str, port: int) -> None:
    """Server config: shell terminal + N VNC-lease workers + N chained RFB targets."""
    sessions = [
        f"""
[[sessions]]
session_id = "{SHELL_SESSION}"
display_name = "Provide Shell Demo"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["demo", "text"]
"""
    ]
    for w in NEST_LEASE_WORKERS:
        sessions.append(
            f"""
[[sessions]]
session_id = "{w}"
display_name = "VNC lease {w}"
connector_type = "shell"
input_mode = "hijack"
auto_start = true
tags = ["vnc-lab"]
"""
        )
    targets = []
    for tgt, p in zip(NEST_TARGETS, NEST_PORTS, strict=True):
        targets.append(
            f"""
[[graphical_targets]]
target_id = "{tgt}"
tenant_id = "lab"
protocol = "rfb"
target_address = "127.0.0.1:{p}"
name = "Nested RFB {tgt}"
enabled = true
width = 1280
height = 936
"""
        )
    body = f"""\
# Auto-generated by record_uterm_vnc_nested_demo.py — do not commit.
[server]
host = "{host}"
port = {port}
public_base_url = "http://127.0.0.1:{port}"
title = "uterm nested VNC demo"

[auth]
mode = "header"
header_mode_acknowledged = true
principal_header = "x-uterm-principal"
role_header = "x-uterm-role"
worker_bearer_token = "{base.LAB_WORKER_TOKEN}"
trusted_proxy_ips = [
  "127.0.0.1", "::1",
  "192.168.5.1", "192.168.5.2", "192.168.65.1", "192.168.65.2",
  "172.17.0.1", "172.18.0.1", "10.0.0.1",
]

[ui]
app_path = "/app"
assets_path = "/_terminal"

[recording]
enabled_by_default = false

[security]
block_private_connector_targets = false
{"".join(sessions)}{"".join(targets)}"""
    path.write_text(body, encoding="utf-8")


def _start_nested_lab(*, name: str, demo_url: str, host_plain: int) -> None:
    """Start one nested lab container; Chromium opens *demo_url*."""
    vnc_lab._remove_container(name)
    result = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            name,
            "--shm-size",
            vnc_lab.DEFAULT_SHM,
            "--add-host=host.docker.internal:host-gateway",
            "-p",
            f"{host_plain}:{vnc_lab.RFB_PLAIN_PORT}",
            "-e",
            f"DEMO_URL={demo_url}",
            "-e",
            f"GEOMETRY={LAB_GEOMETRY}",
            vnc_lab.IMAGE_NAME,
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"docker run {name} failed: {result.stderr.strip()[:400]}")


def _wait_lab_rfb(name: str, *, timeout: float = 40.0) -> bool:
    """Wait until a lab container reports its RFB listener ready."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        chk = subprocess.run(
            ["docker", "exec", name, "test", "-f", "/var/log/vnc-lab/vnc-ready"],
            capture_output=True,
            timeout=8,
            check=False,
        )
        if chk.returncode == 0:
            return True
        time.sleep(0.5)
    return False


def _encode_mp4(source: Path, out: Path, *, fps: int = 25) -> None:
    """Transcode Playwright's webm capture to a QuickTime-playable H.264 MP4."""
    ff = subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(source),
            "-fps_mode",
            "cfr",
            "-r",
            str(fps),
            "-pix_fmt",
            "yuv420p",
            "-c:v",
            "libx264",
            "-crf",
            "20",
            "-preset",
            "medium",
            "-movflags",
            "+faststart",
            str(out),
        ],
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    if ff.returncode != 0 or not out.is_file():
        raise RuntimeError(f"ffmpeg mp4 transcode failed: {(ff.stderr or ff.stdout)[:800]}")


def _acquire_lease(base_url: str, headers: dict[str, str], worker: str) -> str:
    """Acquire a 300s hijack lease on *worker*; return hijack_id."""
    status, payload = base.http_json(
        "POST",
        f"{base_url}/worker/{worker}/hijack/acquire",
        headers=headers,
        body={"owner": "nested-recorder", "lease_s": 300},
    )
    if status != 200 or not isinstance(payload, dict):
        raise RuntimeError(f"lease acquire {worker} failed: {status} {payload!r}")
    return str(payload["hijack_id"])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-dir", default=None)
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--seconds", type=float, default=8.0, help="hold on the final nested view")
    args = parser.parse_args(argv)

    evidence = base._evidence_dir(args.evidence_dir)
    root = base._repo_root()
    shots = evidence / "screenshots"
    shots.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [f"evidence={evidence}"]

    if not vnc_lab._docker_available():
        (evidence / "docker-unavailable.log").write_text("docker missing\n", encoding="utf-8")
        return 2
    if not args.skip_build:
        vnc_lab.build_image(root=root, log_path=evidence / "lab-build.log")

    server_port = base._free_port()
    cfg = evidence / "nested-server.toml"
    _write_nested_config(cfg, host="0.0.0.0", port=server_port)

    env = {**os.environ, "UTERM_TEST_MODE": "1", "UTERM_API_ONLY": "0"}
    log_path = evidence / "nested-server.log"
    cmd = [str(root / ".venv" / "bin" / "uterm"), "server", "--config", str(cfg)]
    if not Path(cmd[0]).is_file():
        cmd = [sys.executable, "-m", "provide.uterm.cli", "server", "--config", str(cfg)]
    log_f = log_path.open("w", encoding="utf-8")
    proc = subprocess.Popen(cmd, cwd=str(root), stdout=log_f, stderr=subprocess.STDOUT, text=True, env=env)

    headers = {
        "x-uterm-principal": "test-admin",
        "x-uterm-role": "admin",
        "x-uterm-tenant": "lab",
        "Content-Type": "application/json",
    }
    base_url = f"http://127.0.0.1:{server_port}"
    metrics: dict[str, object] = {}
    try:
        base.prove.wait_http(f"{base_url}/readyz", timeout=60.0)
        lines.append(f"server_ready={base_url}")

        # Wait for the shell worker to connect, then seed the terminal content.
        connected = False
        for _ in range(80):
            st, body = base.http_json("GET", f"{base_url}/api/sessions/{SHELL_SESSION}", headers=headers)
            if st == 200 and isinstance(body, dict) and body.get("connected"):
                connected = True
                break
            time.sleep(0.15)
        if not connected:
            raise RuntimeError(f"session {SHELL_SESSION} never connected")
        shell_hid, _ = base.acquire_shell(base_url, headers, session=SHELL_SESSION)
        if not shell_hid:
            raise RuntimeError("failed to acquire shell lease")
        for cmd_line in SEED_LINES:
            base.send_shell_keys(base_url, headers, shell_hid, cmd_line)
            time.sleep(0.05)
        lines.append("terminal_seeded=ok")

        # Pre-acquire a VNC hijack lease per level (baked into each DEMO_URL).
        hids = [_acquire_lease(base_url, headers, w) for w in NEST_LEASE_WORKERS]
        lines.append(f"leases={hids}")

        # Start labs innermost first. lab0 shows the terminal; lab i>0 shows lab i-1.
        for i in range(LEVELS):
            if i == 0:
                demo_url = (
                    f"http://{base._HOST_FROM_DOCKER}:{server_port}"
                    f"/_terminal/terminal.html?worker_id={SHELL_SESSION}&role=browser"
                )
            else:
                demo_url = (
                    f"http://{base._HOST_FROM_DOCKER}:{server_port}/_terminal/vnc.html"
                    f"?worker_id={NEST_LEASE_WORKERS[i - 1]}&hijack_id={hids[i - 1]}&target_id={NEST_TARGETS[i - 1]}"
                )
            _start_nested_lab(name=NEST_NAMES[i], demo_url=demo_url, host_plain=NEST_PORTS[i])
            if not _wait_lab_rfb(NEST_NAMES[i]):
                raise RuntimeError(f"lab {NEST_NAMES[i]} RFB never ready")
            lines.append(f"lab{i}_started={NEST_NAMES[i]} url={demo_url}")
            # Give the inner content a beat to paint before the next level attaches.
            time.sleep(3.0)

        # Host records the outermost console (viewing lab2 -> lab1 -> lab0 -> terminal).
        host_page = (
            f"{base_url}/_terminal/vnc.html"
            f"?worker_id={NEST_LEASE_WORKERS[LEVELS - 1]}&hijack_id={hids[LEVELS - 1]}"
            f"&target_id={NEST_TARGETS[LEVELS - 1]}"
        )
        lines.append(f"host_page={host_page}")

        from playwright.sync_api import sync_playwright

        raw_dir = evidence / "nested-video-raw"
        raw_dir.mkdir(exist_ok=True)
        full_png = shots / "uterm-vnc-nested-full.png"
        desktop_png = shots / "uterm-vnc-nested-desktop.png"
        live_webm: Path | None = None
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                viewport={"width": 1440, "height": 900},
                device_scale_factor=1,
                record_video_dir=str(raw_dir),
                record_video_size={"width": 1440, "height": 900},
            )
            context.add_cookies(
                [
                    {"name": "uterm_principal", "value": "test-admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_role", "value": "admin", "domain": "127.0.0.1", "path": "/"},
                    {"name": "uterm_tenant", "value": "lab", "domain": "127.0.0.1", "path": "/"},
                ]
            )
            page = context.new_page()
            page.set_extra_http_headers(
                {"x-uterm-principal": "test-admin", "x-uterm-role": "admin", "x-uterm-tenant": "lab"}
            )
            page.goto(host_page, wait_until="domcontentloaded", timeout=45_000)
            page.wait_for_function(
                "() => document.getElementById('vnc-status')?.dataset?.state === 'connected'",
                timeout=40_000,
            )
            page.wait_for_function(
                "() => { const c = document.querySelector('#vnc-screen canvas');"
                " return c instanceof HTMLCanvasElement && c.width >= 640; }",
                timeout=30_000,
            )
            # Let the full nested cascade settle (each RFB level re-encodes).
            page.wait_for_timeout(int(max(3.0, float(args.seconds)) * 1000))
            page.screenshot(path=str(full_png), full_page=True)
            page.locator("#vnc-screen").screenshot(path=str(desktop_png))
            metrics.update(
                page.evaluate(
                    "() => { const s=document.getElementById('vnc-status'),"
                    " c=document.querySelector('#vnc-screen canvas');"
                    " return {status_state:s?.dataset?.state??null, canvas_w:c?.width??0, canvas_h:c?.height??0,"
                    " title:document.title}; }"
                )
            )
            video = page.video
            context.close()
            browser.close()
            if video is not None:
                try:
                    live_webm = Path(video.path())
                except Exception:  # pragma: no cover - best-effort
                    live_webm = None

        lines.append(f"metrics={json.dumps(metrics)}")
        if metrics.get("status_state") != "connected":
            raise RuntimeError(f"host console never connected: {metrics}")

        video_out = evidence / "uterm-vnc-nested-demo.mp4"
        if live_webm and live_webm.is_file():
            _encode_mp4(live_webm, video_out)
            base._assert_video_not_black(video_out)
            lines.append(f"video={video_out}")

        demo = root / "demo" / "vnc-lab"
        (demo / "screenshots").mkdir(parents=True, exist_ok=True)
        for src, name in ((full_png, "uterm-vnc-nested-full.png"), (desktop_png, "uterm-vnc-nested-desktop.png")):
            (demo / "screenshots" / name).write_bytes(src.read_bytes())
        if video_out.is_file():
            (demo / "uterm-vnc-nested-demo.mp4").write_bytes(video_out.read_bytes())
        (evidence / "nested-summary.log").write_text("\n".join(lines) + "\nnested_proof=ok\n", encoding="utf-8")
        print("\n".join(lines))
        return 0
    except Exception as exc:
        lines.append(f"error={exc}")
        (evidence / "nested-summary.log").write_text("\n".join(lines) + "\nnested_proof=FAIL\n", encoding="utf-8")
        print("\n".join(lines), file=sys.stderr)
        return 1
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        for name in NEST_NAMES:
            vnc_lab._remove_container(name)


if __name__ == "__main__":
    raise SystemExit(main())
